import ProjectDescription

let team = "Q8H6GWJ658"
let releaseVersion = "1.0.0"
let releaseBuild = "22"
let project = Project(name: "MurMurMobile", options: .options(defaultKnownRegions: ["en", "ru", "de", "es", "fr", "fi"], developmentRegion: "en", disableSynthesizedResourceAccessors: true), packages: [
    .local(path: "../../Engine/Core"), .local(path: "../../Engine/Speech"), .local(path: "../../Engine/Translation")
], targets: [
    .target(name: "MurMurMobile", destinations: [.iPhone, .iPad], product: .app,
        bundleId: "app.bshk.murmur.ios", deploymentTargets: .iOS("18.0"),
        infoPlist: .extendingDefault(with: [
            "CFBundleDisplayName": "Murmator", "CFBundleShortVersionString": .string(releaseVersion), "CFBundleVersion": .string(releaseBuild),
            "ITSAppUsesNonExemptEncryption": false,
            "com.apple.developer.translation-ui-provider.network-access": true,
            "NSMicrophoneUsageDescription": "Murmator records and transcribes your voice on this device.",
            "CFBundleDevelopmentRegion": "en", "CFBundleLocalizations": ["en", "ru", "de", "es", "fr", "fi"],
            "NSSupportsLiveActivities": true, "UIBackgroundModes": ["audio"], "UILaunchScreen": [:],
            "CFBundleURLTypes": [["CFBundleURLName": "app.bshk.murmur.ios", "CFBundleURLSchemes": ["murmur"]]],
            "UISupportedInterfaceOrientations": ["UIInterfaceOrientationPortrait", "UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight"],
            "UIFileSharingEnabled": true, "LSSupportsOpeningDocumentsInPlace": false,
            "CFBundleDocumentTypes": [["CFBundleTypeName": "Audio recording", "CFBundleTypeRole": "Viewer", "LSHandlerRank": "Alternate", "LSItemContentTypes": ["public.audio"]]]
        ]), sources: ["Sources/**", "Shared/**", "PageTranslation/PageL10n.swift"], resources: ["Resources/**", "PageTranslation/Resources/Localizations/**"],
        entitlements: .file(path: "MurMur.entitlements"),
        dependencies: [.package(product:"MurmurCore"), .package(product:"MurmurSpeech"), .package(product:"MurmurTranslation"), .target(name:"MurMurWidgets"), .target(name:"MurMurKeyboard"), .target(name:"MurMurTranslationProvider"), .target(name:"MurMurPageTranslation")],
        settings: .settings(base: ["SWIFT_VERSION":"5.0", "DEVELOPMENT_TEAM": .string(team), "CODE_SIGN_STYLE":"Automatic", "ASSETCATALOG_COMPILER_APPICON_NAME":"AppIcon"])),
    .target(name:"MurMurWidgets", destinations:[.iPhone,.iPad], product:.appExtension,
        bundleId:"app.bshk.murmur.ios.widgets", deploymentTargets:.iOS("18.0"),
        infoPlist:.extendingDefault(with:["CFBundleDisplayName":"Murmator", "CFBundleShortVersionString":.string(releaseVersion), "CFBundleVersion":.string(releaseBuild), "NSExtension":["NSExtensionPointIdentifier":"com.apple.widgetkit-extension"]]),
        sources:["Widgets/**","Shared/**"], resources:["Resources/Localizations/**", "Resources/MascotMark.png", "Resources/PrivacyInfo.xcprivacy"], entitlements:.file(path:"Shared.entitlements"),
        dependencies:[.package(product:"MurmurCore")],settings:.settings(base:["SWIFT_VERSION":"5.0","DEVELOPMENT_TEAM":.string(team),"CODE_SIGN_STYLE":"Automatic","APPLICATION_EXTENSION_API_ONLY":"YES"])),
    .target(name:"MurMurKeyboard",destinations:[.iPhone,.iPad],product:.appExtension,
        bundleId:"app.bshk.murmur.ios.keyboard",deploymentTargets:.iOS("18.0"),
        infoPlist:.extendingDefault(with:["CFBundleDisplayName":"Murmator", "CFBundleShortVersionString":.string(releaseVersion), "CFBundleVersion":.string(releaseBuild), "NSExtension":["NSExtensionPointIdentifier":"com.apple.keyboard-service","NSExtensionPrincipalClass":"$(PRODUCT_MODULE_NAME).KeyboardViewController", "NSExtensionAttributes":["IsASCIICapable":false,"PrefersRightToLeft":false,"PrimaryLanguage":"en-US","RequestsOpenAccess":true]]]),
        sources:["Keyboard/**","Shared/KeyboardSessionStore.swift","Shared/StoragePaths.swift", "Shared/TranslationPaths.swift","Shared/Localization.swift","Shared/KeyboardOpenProbeIntent.swift"],resources:["Resources/Localizations/**", "Resources/MascotMark.png", "Resources/PrivacyInfo.xcprivacy"],entitlements:.file(path:"Shared.entitlements"),
        dependencies:[.package(product:"MurmurCore")],settings:.settings(base:["SWIFT_VERSION":"5.0","DEVELOPMENT_TEAM":.string(team),"CODE_SIGN_STYLE":"Automatic","APPLICATION_EXTENSION_API_ONLY":"YES"])),
    .target(name: "MurMurTranslationProvider", destinations: [.iPhone, .iPad], product: .extensionKitExtension,
        bundleId: "app.bshk.murmur.ios.translation", deploymentTargets: .iOS("18.4"),
        infoPlist: .extendingDefault(with: ["CFBundleDisplayName": "Murmator", "CFBundleShortVersionString": .string(releaseVersion), "CFBundleVersion": .string(releaseBuild), "EXAppExtensionAttributes": ["EXExtensionPointIdentifier": "com.apple.public.translation-ui-provider"]]),
        sources: ["TranslationProvider/**", "Sources/CompactTranslationSheet.swift", "Sources/LanguageMenu.swift", "Sources/TranscriptText.swift", "Sources/CorrectedTranscriptView.swift", "Sources/DesignSystem.swift", "Shared/TranslationPaths.swift", "Shared/Localization.swift"],
        resources: ["Resources/Localizations/**", "Resources/PrivacyInfo.xcprivacy", "Resources/MascotMark.png"], entitlements: .file(path: "TranslationProvider.entitlements"),
        dependencies: [.package(product: "MurmurCore"), .package(product: "MurmurTranslation")],
        settings: .settings(base: ["SWIFT_VERSION": "5.0", "DEVELOPMENT_TEAM": .string(team), "CODE_SIGN_STYLE": "Automatic", "APPLICATION_EXTENSION_API_ONLY": "YES"])),
    .target(name: "MurMurPageTranslation", destinations: [.iPhone, .iPad], product: .appExtension,
        bundleId: "app.bshk.murmur.ios.page-translation", deploymentTargets: .iOS("18.0"),
        infoPlist: .extendingDefault(with: ["CFBundleDisplayName": "Murmator", "CFBundleShortVersionString": .string(releaseVersion), "CFBundleVersion": .string(releaseBuild), "NSExtension": ["NSExtensionPointIdentifier": "com.apple.ui-services", "NSExtensionPrincipalClass": "$(PRODUCT_MODULE_NAME).ActionViewController", "NSExtensionAttributes": ["NSExtensionJavaScriptPreprocessingFile": "Page", "NSExtensionActivationRule": ["NSExtensionActivationSupportsWebPageWithMaxCount": 1]]]]),
        sources: ["PageTranslation/ActionViewController.swift", "PageTranslation/PageTranslationView.swift", "Sources/LanguageMenu.swift", "Shared/Localization.swift", "PageTranslation/PageL10n.swift", "Shared/TranslationPaths.swift"], resources: ["PageTranslation/Resources/Page.js", "PageTranslation/Resources/ActionAssets.xcassets", "PageTranslation/Resources/Localizations/**", "Resources/PrivacyInfo.xcprivacy"],
        entitlements: .file(path: "TranslationProvider.entitlements"), dependencies: [.package(product: "MurmurCore"), .package(product: "MurmurTranslation")],
        settings: .settings(base: ["SWIFT_VERSION": "5.0", "DEVELOPMENT_TEAM": .string(team), "CODE_SIGN_STYLE": "Automatic", "APPLICATION_EXTENSION_API_ONLY": "YES", "ASSETCATALOG_COMPILER_APPICON_NAME": "ActionIcon"])),
    .target(name: "MurmatorPageTestHost", destinations: [.iPhone, .iPad], product: .app,
        bundleId: "app.bshk.murmur.ios", deploymentTargets: .iOS("18.0"),
        infoPlist: .extendingDefault(with: ["CFBundleDisplayName": "Murmator Page Tests", "CFBundleShortVersionString": .string(releaseVersion), "CFBundleVersion": .string(releaseBuild), "UILaunchScreen": [:], "NSAppTransportSecurity": ["NSAllowsLocalNetworking": true]]),
        sources: ["PageTranslation/TestSupport/Host/**", "Shared/TranslationPaths.swift"],
        resources: [.folderReference(path: "../../Prototypes/iOS/build/TranslationModels/ct2-enfi"), .folderReference(path: "../../Prototypes/iOS/build/TranslationModels/ct2-fien"), .folderReference(path: "../../Prototypes/iOS/build/TranslationModels/ct2-firu")],
        entitlements: .file(path: "MurMur.entitlements"), dependencies: [.target(name: "MurMurPageTranslation"), .target(name: "MurMurTranslationProvider"), .package(product: "MurmurCore")],
        settings: .settings(base: ["SWIFT_VERSION": "5.0", "DEVELOPMENT_TEAM": .string(team), "CODE_SIGN_STYLE": "Automatic"])),
    .target(name: "MurmatorSafariTests", destinations: [.iPhone, .iPad], product: .uiTests,
        bundleId: "app.bshk.murmur.safaritests", deploymentTargets: .iOS("18.0"), infoPlist: .default,
        sources: ["SafariTranslation/TestSupport/Tests/**"], dependencies: [.target(name: "MurmatorPageTestHost")],
        settings: .settings(base: ["SWIFT_VERSION": "5.0", "DEVELOPMENT_TEAM": .string(team), "CODE_SIGN_STYLE": "Automatic"])),
    .target(name: "MurmatorPageTests", destinations: [.iPhone, .iPad], product: .uiTests,
        bundleId: "app.bshk.murmur.pagetests", deploymentTargets: .iOS("18.0"), infoPlist: .default,
        sources: ["PageTranslation/TestSupport/Tests/**"], dependencies: [.target(name: "MurmatorPageTestHost")],
        settings: .settings(base: ["SWIFT_VERSION": "5.0", "DEVELOPMENT_TEAM": .string(team), "CODE_SIGN_STYLE": "Automatic"])),
    .target(name: "MurMurUITestHost", destinations: [.iPhone, .iPad], product: .app,
        bundleId: "app.bshk.murmur.uitesthost", deploymentTargets: .iOS("18.0"),
        infoPlist: .extendingDefault(with: ["CFBundleDisplayName": "MurMur UI Tests", "CFBundleShortVersionString": .string(releaseVersion), "CFBundleVersion": .string(releaseBuild), "CFBundleDevelopmentRegion": "en", "UILaunchScreen": [:], "NSMicrophoneUsageDescription": "Murmator records and transcribes your voice on this device.", "UIFileSharingEnabled": true, "LSSupportsOpeningDocumentsInPlace": true, "CFBundleDocumentTypes": [["CFBundleTypeName": "Audio recording", "CFBundleTypeRole": "Viewer", "LSHandlerRank": "Alternate", "LSItemContentTypes": ["public.audio"]]]]),
        sources: ["Sources/MurMurApp.swift", "Sources/KeyboardProbeHostView.swift", "Sources/KeyboardDictationView.swift", "Sources/DesignSystem.swift", "Sources/MurmurMascot.swift", "Sources/ListActions.swift", "Sources/NoteListRow.swift", "Sources/NotesView.swift", "Sources/NoteDetailView.swift", "Sources/RecordingAudioControls.swift", "Sources/ConversationLogView.swift", "Sources/RecordingView.swift", "Sources/CorrectedTranscriptView.swift", "Sources/TranscriptText.swift", "Sources/SetupViews.swift", "Sources/SpeechPriorityPicker.swift", "Sources/PageTranslationHelpView.swift", "PageTranslation/PageL10n.swift", "Sources/AboutView.swift", "Sources/TranslationSetupView.swift", "Sources/TextTranslationView.swift", "Sources/CompactTranslationSheet.swift", "Sources/LanguageMenu.swift", "Sources/TranslationStorageSetup.swift", "Sources/MemoryView.swift", "Sources/StorageView.swift", "Sources/AudioImportView.swift", "Shared/AudioImportJob.swift", "Shared/WidgetState.swift", "Widgets/MurMurControlsView.swift", "Keyboard/KeyboardViewController.swift", "Shared/KeyboardSessionStore.swift", "Sources/OnboardingView.swift", "Sources/LanguageSetupView.swift", "Shared/StoragePaths.swift", "Shared/TranslationPaths.swift", "Shared/RecordingAttributes.swift", "Shared/LanguageLibrary.swift", "Shared/Localization.swift", "UITestHost/**"],
        resources: ["Resources/**", "PageTranslation/Resources/Localizations/**"], dependencies: [.package(product: "MurmurCore")],
        settings: .settings(base: ["SWIFT_VERSION": "5.0", "CODE_SIGNING_ALLOWED": "NO", "SWIFT_ACTIVE_COMPILATION_CONDITIONS": "$(inherited) DEBUG MURMUR_UI_HOST", "ASSETCATALOG_COMPILER_APPICON_NAME": "AppIcon"])),
    .target(name: "CompactTranslationSheetTests", destinations: [.iPhone, .iPad], product: .uiTests,
        bundleId: "app.bshk.murmur.compactsheettests", deploymentTargets: .iOS("18.0"), infoPlist: .default,
        sources: ["CompactSheetTests/**"], dependencies: [.target(name: "MurMurUITestHost")],
        settings: .settings(base: ["SWIFT_VERSION": "5.0", "CODE_SIGNING_ALLOWED": "NO"])),
    .target(name:"MurMurMobileUITests",destinations:[.iPhone,.iPad],product:.uiTests,
        bundleId:"app.bshk.murmur.ios.uitests",deploymentTargets:.iOS("18.0"),
        infoPlist:.default,sources:["Tests/**"],dependencies:[.target(name:"MurMurMobile")],
        settings:.settings(base:["SWIFT_VERSION":"5.0","DEVELOPMENT_TEAM":.string(team),"CODE_SIGN_STYLE":"Automatic"]))
], schemes: [.scheme(name: "MurmatorSafariTestHost", shared: true, buildAction: .buildAction(targets: ["MurmatorPageTestHost"]), testAction: .targets(["MurmatorSafariTests"], configuration: "Debug"), runAction: .runAction(configuration: "Debug")), .scheme(name: "CompactTranslationSheet", shared: true, buildAction: .buildAction(targets: ["MurMurUITestHost"]), testAction: .targets(["CompactTranslationSheetTests"], configuration: "Debug"), runAction: .runAction(configuration: "Debug")), .scheme(name: "MurmatorPageTestHost", shared: true, buildAction: .buildAction(targets: ["MurmatorPageTestHost"]), testAction: .targets(["MurmatorPageTests"], configuration: "Debug"), runAction: .runAction(configuration: "Debug"))])
