// Generated by Scripts/generate-translation-manifest.py — do not edit by hand.
//
// Each entry pins the exact bytes Murmur will accept for one direction.
// `model` digests are corroborated against the hash Mozilla publishes in
// models/<tier>/<pair>/metadata.json; the tier is noted per direction
// because the mirror carries the best available one rather than a
// uniform tier. `vocab` and `lexicon` have no Mozilla-published digest,
// so they are pinned from bytes fetched when this file was generated.

/// SHA-256 and download size of every translation model file, by direction.
enum TranslationModelDigests {
    struct File {
        let sha256: String
        /// Compressed length, which is what the transfer actually moves
        /// and therefore what a progress fraction is denominated in.
        let downloadBytes: Int
    }

    struct Entry {
        let model: File
        let vocab: File
        let lexicon: File

        var totalDownloadBytes: Int {
            model.downloadBytes + vocab.downloadBytes + lexicon.downloadBytes
        }
    }

    static let all: [String: Entry] = [
        // bgen: base-memory, 31.6 MB unpacked, 25.0 MB transferred
        "bgen": Entry(
            model: File(sha256: "78f7e6e1435cc2d4a29cf597f493187fe29ddb9ce9d3766c287e2e6d37052d01",
                         downloadBytes: 22399269),
            vocab: File(sha256: "4bafad5fcc0e771ed82233d1e99d69dcb96487b430702f7e688615c8a61f3df4",
                         downloadBytes: 434940),
            lexicon: File(sha256: "e661dfdd88aa9ff9606f237a60c910d97c2e710960199589579f628c5d8aa899",
                         downloadBytes: 2187053)),
        // csen: base-memory, 31.6 MB unpacked, 25.7 MB transferred
        "csen": Entry(
            model: File(sha256: "c815273b31074492eaab0ccd78d33d7ac16f94088707ab2492abaedcb9ee0b75",
                         downloadBytes: 22830296),
            vocab: File(sha256: "ee4b8ce15c8e1237c5f7a2d04741341beb0a5d5c09820f7ec08f13ee2b212755",
                         downloadBytes: 412691),
            lexicon: File(sha256: "eba6bd9575251525f1941640ea0b6527a06e72a46421579eafea04d635ee20a8",
                         downloadBytes: 2493702)),
        // deen: base-memory, 31.6 MB unpacked, 25.4 MB transferred
        "deen": Entry(
            model: File(sha256: "3e6f7c2c2425d10824797270b382bee718ff34af2cab9308841c82ca46dc6f20",
                         downloadBytes: 22403755),
            vocab: File(sha256: "69f730becafa48e3bb2c244eab66456877c08959a02f2bd5519b5a3088b62f9c",
                         downloadBytes: 413879),
            lexicon: File(sha256: "113b98460468360cca68c042e1cddf49c4e1931cbb975ed04349c9a3bd607010",
                         downloadBytes: 2626658)),
        // enbg: base-memory, 31.6 MB unpacked, 25.4 MB transferred
        "enbg": Entry(
            model: File(sha256: "e2b30db98ac6706efc893067a74e51f36f015a8f820fe8a4f0f5052fa6a22f30",
                         downloadBytes: 23432015),
            vocab: File(sha256: "4bafad5fcc0e771ed82233d1e99d69dcb96487b430702f7e688615c8a61f3df4",
                         downloadBytes: 434940),
            lexicon: File(sha256: "93d4ca4412db269cc4164cbfa04c08edd0f65690c8264d6215a0522d4a13ec1a",
                         downloadBytes: 1548577)),
        // encs: base-memory, 31.6 MB unpacked, 25.5 MB transferred
        "encs": Entry(
            model: File(sha256: "1d7855f91c3e2b8ef79fbea62707d46ceb8a1ad01834ef6dd500f32a7006cc2c",
                         downloadBytes: 23192301),
            vocab: File(sha256: "ee4b8ce15c8e1237c5f7a2d04741341beb0a5d5c09820f7ec08f13ee2b212755",
                         downloadBytes: 412691),
            lexicon: File(sha256: "699b9b59fe3acbcddf831380024b2e139f2cbe225dce96d59ade2b159318f58b",
                         downloadBytes: 1896925)),
        // ende: base-memory, 31.6 MB unpacked, 25.7 MB transferred
        "ende": Entry(
            model: File(sha256: "8df29d9494d19f47fd5d97c6a73474c6f657e9f81c1a607c431d02befdf3810f",
                         downloadBytes: 22992073),
            vocab: File(sha256: "69f730becafa48e3bb2c244eab66456877c08959a02f2bd5519b5a3088b62f9c",
                         downloadBytes: 413879),
            lexicon: File(sha256: "7ed39f1cffbd68a27ddf05bbfe068de2060f1d7e69f1a20e27ae923551dd7393",
                         downloadBytes: 2314750)),
        // enes: base-memory, 31.6 MB unpacked, 25.4 MB transferred
        "enes": Entry(
            model: File(sha256: "3b1c399511c01c84c36fae5c0524df44096288efdc8236e182b5c97d7ad2244c",
                         downloadBytes: 22698792),
            vocab: File(sha256: "5ae254fa9b15aa182e70fd2a6186b1333c63a29a48043a9224c6aa4fcac058ad",
                         downloadBytes: 409312),
            lexicon: File(sha256: "7d51237c0a07027dcd61643cfbbb0f8c48597d19907ef53d2cae9d6bec2cf25c",
                         downloadBytes: 2265250)),
        // enet: base-memory, 31.6 MB unpacked, 25.2 MB transferred
        "enet": Entry(
            model: File(sha256: "36bdc87f8d500861a5d286ebd3ea58df530da87e31b8a233f5e9c46c300c281d",
                         downloadBytes: 22951751),
            vocab: File(sha256: "89a3deea4ae7d674fb46a4dae39135dd4dfaac9786f2868d0b5bc5c0aca2ef83",
                         downloadBytes: 414262),
            lexicon: File(sha256: "259c60582f49449c226a6e5a369481c68322013f367e459e54c595686c05d4d8",
                         downloadBytes: 1865410)),
        // enfi: base-memory, 31.6 MB unpacked, 24.9 MB transferred
        "enfi": Entry(
            model: File(sha256: "88b0caa4cc6980d632801cb2b1950748f1dc43ad2ac83678917ad86c720b5cdd",
                         downloadBytes: 22580027),
            vocab: File(sha256: "6a866911427f2916609ae89c7f2f04a78de3fdd8aa183039ecba986635d4f246",
                         downloadBytes: 414280),
            lexicon: File(sha256: "26e95a87f87e4b0fa9a35524cf9fea691204504453877ba4ac81ccc66af1488c",
                         downloadBytes: 1875557)),
        // enfr: base-memory, 31.6 MB unpacked, 25.8 MB transferred
        "enfr": Entry(
            model: File(sha256: "6322e296d4fecfe395a8d5723da4ec37ecbe6d7613bb1dfcf4b28e2a47498b68",
                         downloadBytes: 23045432),
            vocab: File(sha256: "783abf3abe075afdf8d85d233994bef2c3a064e935ab1bed946820aff6ac002a",
                         downloadBytes: 409706),
            lexicon: File(sha256: "2585ed98d3af0bc949865aedeb390493d591f56870814376e73e4144c41ed059",
                         downloadBytes: 2297334)),
        // enhu: base-memory, 31.6 MB unpacked, 25.9 MB transferred
        "enhu": Entry(
            model: File(sha256: "ec0c210d09cd5d8a5edf7a50462db0a8fb5dd78d03bbc6d4d72d91074f0490e4",
                         downloadBytes: 23710206),
            vocab: File(sha256: "2eee837cfdcc45c091d025f585d3fcdb293db7794e316b38a0aeff8c47a659e0",
                         downloadBytes: 405720),
            lexicon: File(sha256: "f3d1e61003597d1cc9d87e05d2b398a7ae2b3941e3f96947764aac239df1a808",
                         downloadBytes: 1768398)),
        // enit: base-memory, 31.6 MB unpacked, 26.5 MB transferred
        "enit": Entry(
            model: File(sha256: "248f47568788ecc351da7e5e07064d4153b4f71e011364ae2c931ffeec4d1cc2",
                         downloadBytes: 23892889),
            vocab: File(sha256: "3ef0211d4ae6db21440892f180f2019fe2bfc110a330ffa9d2eca9665e4f2bc5",
                         downloadBytes: 407598),
            lexicon: File(sha256: "8b21914804625b2777dae7fdb636eb78f02a3eb8b7bceaa50f29ac740961da93",
                         downloadBytes: 2209348)),
        // ennl: base-memory, 31.6 MB unpacked, 26.0 MB transferred
        "ennl": Entry(
            model: File(sha256: "7e8402da61972dc2fdcf7147c7f1e12f7916a6d9349514ee7a731288357575a9",
                         downloadBytes: 23386633),
            vocab: File(sha256: "c09588ca5662b230ed65bd39a07f58d9f7dd21c3a19e4aeb1bff39bf3b297c56",
                         downloadBytes: 410222),
            lexicon: File(sha256: "bb4922718f8ca6d746ad090c0a88110a664dc050ee3f311bce33698b4e1679e9",
                         downloadBytes: 2155034)),
        // enpl: base-memory, 31.6 MB unpacked, 24.9 MB transferred
        "enpl": Entry(
            model: File(sha256: "b0b59716bcc8f46b8dc6ab5c32a2732acaad42a5a6d9ae9b472526a1bb0d71d4",
                         downloadBytes: 22577447),
            vocab: File(sha256: "2000f182efa8ce5f69bc3f9e574666b5bc2c0af684eedd32f69d15aa9021ea85",
                         downloadBytes: 413194),
            lexicon: File(sha256: "d7d7b364673f633763c9f8f2e8ee9c7a184e92f4086e8b84abe870a2a8dbe5d5",
                         downloadBytes: 1874327)),
        // enpt: base-memory, 31.6 MB unpacked, 25.9 MB transferred
        "enpt": Entry(
            model: File(sha256: "07892fd2544ee79dcb643615d8f2debb9793fae16842e87c328e27a3dd26a770",
                         downloadBytes: 23340019),
            vocab: File(sha256: "d9f46182823d5bbc84201252b2dfcac28f63e561f0ec827ed858f241864c9def",
                         downloadBytes: 408686),
            lexicon: File(sha256: "ccb4c31c9e1899d77a200e71a86958e6ef6c8649627d0bbf3f873b57d9f236bd",
                         downloadBytes: 2117608)),
        // enru: base, 43.0 MB unpacked, 32.5 MB transferred
        "enru": Entry(
            model: File(sha256: "0ef9a209c5edc46692750e7505b3695655b1c7c3ec73058b641201ef18c481ce",
                         downloadBytes: 30698731),
            vocab: File(sha256: "56ee63e14e8cb926c394242adc3ed7cc602644c3d33058cff2ce2959d52a6258",
                         downloadBytes: 419005),
            lexicon: File(sha256: "3587f93c10c1d457f874c2ba7ff4d5e2686fdaf7f3fd179cfefeacab3c6990b9",
                         downloadBytes: 1348215)),
        // ensl: base-memory, 31.6 MB unpacked, 24.8 MB transferred
        "ensl": Entry(
            model: File(sha256: "a34fc5cc2f52733f64e37f8512cf1ddc4723c08a7a1a59d01fc2b6e641fc2280",
                         downloadBytes: 22669559),
            vocab: File(sha256: "7cd295383c46824c05a05db76b543d3595f2516537dd22b77190a45c8919224d",
                         downloadBytes: 398763),
            lexicon: File(sha256: "2190798297bc12505f917189defcf451ab5bd2e815bc05df244dc291dc2ae63b",
                         downloadBytes: 1741316)),
        // enuk: base-memory, 31.6 MB unpacked, 24.9 MB transferred
        "enuk": Entry(
            model: File(sha256: "ed8bb4a811e1c45a259e91052080d25e5c8b4e2df0e59cb1521c04a57855ef97",
                         downloadBytes: 22864374),
            vocab: File(sha256: "4dd6a91feff71e745395dcc0d52f885848ca0d843d5f70628ca51b3be1b70b45",
                         downloadBytes: 436850),
            lexicon: File(sha256: "dbfd4f8dc95da9c575164f7fc95ef00a2fb5f7d9f51b656559f99eeebdb57c87",
                         downloadBytes: 1564122)),
        // esen: base-memory, 31.6 MB unpacked, 26.2 MB transferred
        "esen": Entry(
            model: File(sha256: "4aed7734152ae0045d1a69ae49c86cfda18f53c61f90e95e1d1de1c7c7c3b033",
                         downloadBytes: 23288494),
            vocab: File(sha256: "5ae254fa9b15aa182e70fd2a6186b1333c63a29a48043a9224c6aa4fcac058ad",
                         downloadBytes: 409312),
            lexicon: File(sha256: "e2610211d3b9577d012638fe7e7e74ed7b4b708ce96b9e792e67c282a6492daa",
                         downloadBytes: 2543246)),
        // eten: base-memory, 31.6 MB unpacked, 25.5 MB transferred
        "eten": Entry(
            model: File(sha256: "df844b3a6df906b2e0682fb7765694f35b351854db00f964896d9c8c365fbff3",
                         downloadBytes: 22785077),
            vocab: File(sha256: "89a3deea4ae7d674fb46a4dae39135dd4dfaac9786f2868d0b5bc5c0aca2ef83",
                         downloadBytes: 414262),
            lexicon: File(sha256: "ad9750f3b41cb5686e561608271a0dc935fc827bf43226e579a6f48a3f6b5f11",
                         downloadBytes: 2321326)),
        // fien: base-memory, 31.6 MB unpacked, 25.9 MB transferred
        "fien": Entry(
            model: File(sha256: "e3887341f18bcc7787d9b59eb1229b56eefce18d49b7ebf1e62c55d65a377321",
                         downloadBytes: 22935246),
            vocab: File(sha256: "6a866911427f2916609ae89c7f2f04a78de3fdd8aa183039ecba986635d4f246",
                         downloadBytes: 414280),
            lexicon: File(sha256: "8bad431e07b062ba47f363b76e4656cc743fd608316d8a4830a4315e44ac9abb",
                         downloadBytes: 2580517)),
        // fren: base-memory, 31.6 MB unpacked, 26.2 MB transferred
        "fren": Entry(
            model: File(sha256: "15f997bc0d13808b0b0fbd0786e684a3c8a52adcd8071844b76123fdacbf2b90",
                         downloadBytes: 23175075),
            vocab: File(sha256: "783abf3abe075afdf8d85d233994bef2c3a064e935ab1bed946820aff6ac002a",
                         downloadBytes: 409706),
            lexicon: File(sha256: "87c6752ea908f5f0347c10ac0cf7d80d9c2f4f20c81c90168f3e8230b56d4440",
                         downloadBytes: 2649934)),
        // huen: tiny, 17.1 MB unpacked, 16.4 MB transferred
        "huen": Entry(
            model: File(sha256: "518356dbb0c071739318601963a87580fb41732652f52bd3635246330c186d9e",
                         downloadBytes: 13181613),
            vocab: File(sha256: "0db772702235b02d1f29abafb7a49ed77e54c60245b3a46e90716e74263aedd6",
                         downloadBytes: 419908),
            lexicon: File(sha256: "fff56b2501258ec4c46a8fc715caee7aeb15d853f859cdfacd3ef9903ed2fff1",
                         downloadBytes: 2778202)),
        // iten: base-memory, 31.6 MB unpacked, 26.2 MB transferred
        "iten": Entry(
            model: File(sha256: "21b70978ce2f3b4da7a06b5de86a09abe3acd30b9eee1b2ebb3582b9bad790bf",
                         downloadBytes: 23301774),
            vocab: File(sha256: "3ef0211d4ae6db21440892f180f2019fe2bfc110a330ffa9d2eca9665e4f2bc5",
                         downloadBytes: 407598),
            lexicon: File(sha256: "0700d6d70b30490e68ff9deca0b45b80310745b491855bde3a13e1692d0cbce1",
                         downloadBytes: 2532929)),
        // nlen: base-memory, 31.6 MB unpacked, 25.7 MB transferred
        "nlen": Entry(
            model: File(sha256: "ff987741ff15a5d94fff16cbef28f2b0a85a6e9547d982fad60ac09d16d11270",
                         downloadBytes: 22647743),
            vocab: File(sha256: "c09588ca5662b230ed65bd39a07f58d9f7dd21c3a19e4aeb1bff39bf3b297c56",
                         downloadBytes: 410222),
            lexicon: File(sha256: "811ac8f9dcbd12706e2d73a7057a7bbe6b9f0607d15170ffe9439977e8229b41",
                         downloadBytes: 2616098)),
        // plen: base-memory, 31.6 MB unpacked, 25.5 MB transferred
        "plen": Entry(
            model: File(sha256: "06dbab3baa3bbceab746bc6a3bba807878f38536382c03acddf59d3edf3b5d94",
                         downloadBytes: 22630393),
            vocab: File(sha256: "2000f182efa8ce5f69bc3f9e574666b5bc2c0af684eedd32f69d15aa9021ea85",
                         downloadBytes: 413194),
            lexicon: File(sha256: "b295dfefa7022a62e105276e8c39fdfd67bffe588f4fd78583edd4e04ee0cb3b",
                         downloadBytes: 2489764)),
        // pten: base-memory, 31.6 MB unpacked, 25.6 MB transferred
        "pten": Entry(
            model: File(sha256: "7b854f1ec5a485dd33efd7c1bc01dd7d5a57f566957c5e47722af333f0ce9157",
                         downloadBytes: 22700409),
            vocab: File(sha256: "d9f46182823d5bbc84201252b2dfcac28f63e561f0ec827ed858f241864c9def",
                         downloadBytes: 408686),
            lexicon: File(sha256: "2685d8b6530be92a4db4cc61f15a097eb114552be15cb6c1699e9d2d99d24470",
                         downloadBytes: 2487847)),
        // ruen: tiny, 17.1 MB unpacked, 15.0 MB transferred
        "ruen": Entry(
            model: File(sha256: "b1d85c13cfbb05e1d326dd6f0fb5ef270a2011b547450260f96567a93f446c94",
                         downloadBytes: 12613599),
            vocab: File(sha256: "93bdc941b16e523695c319f74778bca9fd8b75a25ad75020cdc98aef74cdc0fc",
                         downloadBytes: 419860),
            lexicon: File(sha256: "f654693577505fd38b1f3d220cdd4ffffbb45afb900a60cf751f0724eadc74e0",
                         downloadBytes: 1962008)),
        // slen: base-memory, 31.6 MB unpacked, 26.3 MB transferred
        "slen": Entry(
            model: File(sha256: "9d15df58b60048366de4f7b6e727157ffdaea3a0fd1c1759ce232b057e2f991c",
                         downloadBytes: 23730414),
            vocab: File(sha256: "54ed331d3435e2bdc5b02462180197b77631f466fc0e61897b5469449857dd2b",
                         downloadBytes: 398535),
            lexicon: File(sha256: "f456a49e437ccb4a547e4b51480e29c8b83f11e26a3713af35b078cd4dd255cc",
                         downloadBytes: 2138548)),
        // uken: tiny, 17.1 MB unpacked, 14.9 MB transferred
        "uken": Entry(
            model: File(sha256: "2e7b8bc9d2569d8b4ae244e964cdc343a0aa3735cc83ecb664be84a37cb45f48",
                         downloadBytes: 12677432),
            vocab: File(sha256: "8b51480dfc4ca2d7a08d2bfdaa9e57353ca97e6cf3d5f9aba4c0179d3665bfc0",
                         downloadBytes: 415266),
            lexicon: File(sha256: "32b5e0df493671a223cb5cb32430181cbb7fe6b5562c91dbc3d35410d37e5ff6",
                         downloadBytes: 1790588)),
    ]
}
