import Compression
import CryptoKit
import Foundation

/// Fetches Bergamot translation models for one language direction into the
/// layout `Translator` reads: `<root>/moz-<pair>/` holding three model files and
/// a generated `config.bergamot.yml`.
///
/// Shaped after `OnboardingDownloader` — an actor holding progress state,
/// snapshotting it out to a `@MainActor` callback, entered through one static
/// `download`. It does not share that type's machinery, because it cannot:
/// `ModelUtils.resolveOrDownloadModel` resolves Hugging Face *repos* of
/// safetensors into the MLX cache, and these are three loose gzipped files
/// verified against a digest Mozilla publishes separately. The shape is copied;
/// the transport is not.
///
/// ## Where the bytes come from, and why that is safe
///
/// Mozilla publishes these models in `mozilla/firefox-translations-models`, but
/// the weight files there are Git-LFS pointers whose objects now answer
/// **410 Gone** — that repository can no longer serve them. What it does still
/// serve is `models/<tier>/<pair>/metadata.json`, a small plain file carrying
/// the SHA-256 of the model weights. The bytes come from a community mirror.
///
/// Nothing downloaded is trusted. Every file is checked against a digest pinned
/// in `TranslationModelDigests`, generated by
/// `Scripts/generate-translation-manifest.py`, which corroborates each model
/// digest against Mozilla's published hash. The mirror is transport only: a
/// substituted file fails `verify(_:against:)` and the download throws.
///
/// One measured caveat, recorded because it is not obvious: the mirror carries
/// the best tier available per direction, not one tier throughout — `ruen` is
/// the 17 MB tiny model while `deen` and `fien` are the 32 MB ones. Every
/// direction still matches *some* published Mozilla hash; the tier is noted per
/// entry in the generated manifest.
public actor TranslationDownloader {
    /// Progress for one direction, in bytes actually transferred.
    public struct Progress: Sendable {
        /// Received over total compressed bytes for all three files (0…1).
        ///
        /// Denominated in transferred bytes, not files completed: the three
        /// files differ by more than an order of magnitude, so a per-file
        /// fraction would sit still through the long one and then leap.
        public var fraction = 0.0
        /// Bytes received so far across the whole direction.
        public var receivedBytes: Int64 = 0
        /// Total to transfer, known up front from the pinned manifest.
        public var totalBytes: Int64 = 0
        /// The file currently arriving, for a label.
        public var file = ""
        public init() {}
    }

    /// Fetches one URL, reporting cumulative bytes as they arrive.
    ///
    /// Injectable so progress reporting can be tested without a network: a fake
    /// can deliver known chunk sizes and the assertions stay deterministic.
    public typealias Fetch = @Sendable (URL, @escaping @Sendable (Int64) -> Void) async throws -> Data

    /// One downloadable file, the digest its contents must match, and how many
    /// bytes it costs to fetch.
    ///
    /// `sha256` is mandatory, and deliberately not optional. Every file here is
    /// loaded by the engine — the vocabulary and the lexical shortlist steer
    /// decoding just as the weights do — so an unpinned one is an unverified
    /// input from a mirror nobody audits. An optional digest would let a
    /// direction be added with verification silently skipped; requiring it
    /// makes that a compile error instead.
    ///
    /// The digest covers the *decompressed* file: it is what the engine loads,
    /// so verifying it catches both a corrupted transfer and a substituted
    /// archive. `downloadBytes` is the *compressed* length, because that is
    /// what travels.
    public struct Artifact: Sendable {
        public let remoteName: String
        public let localName: String
        public let sha256: String
        public let downloadBytes: Int

        public init(remoteName: String, localName: String, sha256: String, downloadBytes: Int) {
            self.remoteName = remoteName
            self.localName = localName
            self.sha256 = sha256
            self.downloadBytes = downloadBytes
        }
    }

    /// Where to fetch from and how the files are named there. Configurable so a
    /// mirror change is a value change, not an edit to the download logic.
    public struct Source: Sendable {
        /// Directory URL under which each direction has a folder.
        public let baseURL: URL
        /// `ruen` → the remote folder name. Mirrors differ: `ru-en` and `ru_en`
        /// are both in use.
        public let directoryName: @Sendable (String) -> String
        /// Suffix on remote files; "" when they are stored uncompressed.
        public let compressionSuffix: String

        public init(baseURL: URL,
                    directoryName: @escaping @Sendable (String) -> String,
                    compressionSuffix: String) {
            self.baseURL = baseURL
            self.directoryName = directoryName
            self.compressionSuffix = compressionSuffix
        }

        /// Gzipped mirror of the Mozilla models, pinned to one revision so a
        /// later push cannot change what a released Murmur downloads.
        public static let mozillaMirror = Source(
            baseURL: URL(string:
                "https://huggingface.co/mukowaty/firefox-translations/resolve/main")!,
            directoryName: { pair in
                let cut = pair.index(pair.startIndex, offsetBy: 2)
                return "\(pair[..<cut])-\(pair[cut...])"
            },
            compressionSuffix: ".gz")
    }

    public enum Err: Error, Equatable {
        case httpStatus(Int, file: String)
        /// The bytes are not what the manifest pins. Never retried silently: a
        /// mismatch means the mirror is wrong or hostile, and quietly
        /// translating with unknown weights is worse than not translating.
        case digestMismatch(file: String, expected: String, actual: String)
        /// No pinned digests for this direction, so nothing can be verified.
        /// Refused rather than downloaded unchecked.
        case unpinnedDirection(String)
        case notGzip(file: String)
        case inflateFailed(file: String)
        case insufficientSpace(needed: Int64, available: Int64)
    }

    private let source: Source
    private let root: URL
    private let fetcher: Fetch
    private let onProgress: @MainActor @Sendable (Progress) -> Void
    private var progress = Progress()
    /// Bytes from files already finished, so the fraction keeps climbing across
    /// file boundaries instead of restarting at each one.
    private var completedBytes: Int64 = 0

    private init(source: Source,
                 root: URL,
                 fetcher: @escaping Fetch,
                 onProgress: @escaping @MainActor @Sendable (Progress) -> Void) {
        self.source = source
        self.root = root
        self.fetcher = fetcher
        self.onProgress = onProgress
    }

    /// Download one direction, reporting fractions on the main actor.
    ///
    /// Returns without touching the network when the direction is already
    /// complete on disk, so this is safe to call before every translation.
    ///
    /// Concurrent calls for the same direction and root share one download
    /// rather than racing. Note the consequence: the second caller's
    /// `onProgress` never fires, because there is only one download to report
    /// on. It still gets the finished directory or the same error.
    @discardableResult
    public static func download(
        pair: LanguagePair,
        into root: URL,
        from source: Source = .mozillaMirror,
        fetcher: @escaping Fetch = TranslationDownloader.streamingFetch,
        onProgress: @escaping @MainActor @Sendable (Progress) -> Void = { _ in }
    ) async throws -> URL {
        let downloader = TranslationDownloader(source: source, root: root,
                                               fetcher: fetcher, onProgress: onProgress)
        let key = "\(root.standardizedFileURL.path)|\(pair.modelDirectoryName)"
        return try await awaitShared(key: key) {
            try await downloader.run(pair: pair)
        }
    }

    /// Holds one in-flight download per `(root, direction)`, and keeps it alive
    /// exactly as long as somebody is waiting on it.
    ///
    /// `TranslationDownloader` is an actor, but a fresh one is built per call,
    /// so its isolation serialises nothing across callers. Without this, two
    /// concurrent downloads of the same direction would publish over each
    /// other — and the loser could delete a directory the winner had already
    /// put in place, leaving an installation that is neither present nor
    /// absent. Sharing the task also avoids fetching 20 MB twice.
    ///
    /// Waiters are counted rather than assumed, because sharing a task means no
    /// single caller may cancel it: abandoning one language while another
    /// caller still wants the same pair must not cut that caller off. The
    /// download stops only when the last waiter leaves — which is what makes
    /// scrubbing through the picker stop the network instead of merely stopping
    /// the wait.
    /// Internal rather than private so the join/leave invariants can be tested
    /// directly: the cancelled-entry window they close is a race that a
    /// timing-based test cannot reliably reproduce.
    actor Coordinator {
        static let shared = Coordinator()

        private struct Entry {
            let task: Task<URL, Error>
            /// One token per waiter. A set, not a count, so a waiter that both
            /// cancels and then completes cannot decrement twice.
            var waiters: Set<UUID>
        }

        private var inFlight: [String: Entry] = [:]

        func join(key: String,
                  work: @escaping @Sendable () async throws -> URL) -> (Task<URL, Error>, UUID) {
            let token = UUID()
            // A cancelled task is never joined. `leave` cancels and unregisters,
            // but it runs as its own hop onto this actor, so there is a window
            // where a cancelled entry is still listed. Picking a language,
            // switching away, and picking it again lands squarely in it — and
            // joining there would hand back a task that fails instantly, so the
            // model would silently never download.
            if var existing = inFlight[key], !existing.task.isCancelled {
                existing.waiters.insert(token)
                inFlight[key] = existing
                return (existing.task, token)
            }
            let task = Task { try await work() }
            inFlight[key] = Entry(task: task, waiters: [token])
            return (task, token)
        }

        /// Drop one waiter; cancel the shared download when the last one goes.
        func leave(key: String, token: UUID) {
            guard var entry = inFlight[key] else { return }
            entry.waiters.remove(token)
            if entry.waiters.isEmpty {
                entry.task.cancel()
                inFlight[key] = nil
            } else {
                inFlight[key] = entry
            }
        }
    }

    /// Await a shared download, leaving cleanly whether it finishes, fails, or
    /// this caller is cancelled.
    private static func awaitShared(key: String,
                                    work: @escaping @Sendable () async throws -> URL) async throws -> URL {
        let (task, token) = await Coordinator.shared.join(key: key, work: work)
        do {
            let url = try await withTaskCancellationHandler {
                try await task.value
            } onCancel: {
                Task { await Coordinator.shared.leave(key: key, token: token) }
            }
            await Coordinator.shared.leave(key: key, token: token)
            return url
        } catch {
            await Coordinator.shared.leave(key: key, token: token)
            throw error
        }
    }

    /// Whether every file the engine needs is already present.
    ///
    /// Presence only — the digest was checked when the file was written, and
    /// re-hashing 17 MB before each utterance would cost more than it protects.
    public static func isInstalled(pair: LanguagePair, in root: URL) -> Bool {
        guard let items = try? artifacts(for: pair) else { return false }
        let directory = root.appendingPathComponent(pair.modelDirectoryName)
        return items.allSatisfy {
            FileManager.default.fileExists(
                atPath: directory.appendingPathComponent($0.localName).path)
        } && FileManager.default.fileExists(
            atPath: directory.appendingPathComponent("config.bergamot.yml").path)
    }

    /// Total compressed bytes for one direction, from the pinned manifest, or
    /// nil when the direction is unpinned.
    ///
    /// Public because a caller spanning several directions — a pivot is two —
    /// has to know the whole size before the first byte moves. Without it the
    /// only honest bar for a pivot would be per-leg, and legs are not equal:
    /// 17 MB followed by 43 MB is not two halves.
    public static func expectedDownloadBytes(for pair: LanguagePair) -> Int64? {
        guard let pinned = TranslationModelDigests.all["\(pair.source)\(pair.target)"] else {
            return nil
        }
        return Int64(pinned.totalDownloadBytes)
    }

    /// The three files one direction needs, in the naming Bergamot expects.
    ///
    /// Throws for a direction with no pinned digests rather than returning
    /// artifacts that cannot be checked.
    static func artifacts(for pair: LanguagePair) throws -> [Artifact] {
        let p = "\(pair.source)\(pair.target)"
        guard let pinned = TranslationModelDigests.all[p] else {
            throw Err.unpinnedDirection(p)
        }
        return [
            Artifact(remoteName: "model.\(p).intgemm.alphas.bin",
                     localName: "model.\(p).intgemm.alphas.bin",
                     sha256: pinned.model.sha256,
                     downloadBytes: pinned.model.downloadBytes),
            Artifact(remoteName: "vocab.\(p).spm", localName: "vocab.\(p).spm",
                     sha256: pinned.vocab.sha256,
                     downloadBytes: pinned.vocab.downloadBytes),
            Artifact(remoteName: "lex.50.50.\(p).s2t.bin",
                     localName: "lex.50.50.\(p).s2t.bin",
                     sha256: pinned.lexicon.sha256,
                     downloadBytes: pinned.lexicon.downloadBytes),
        ]
    }

    private func run(pair: LanguagePair) async throws -> URL {
        let directory = root.appendingPathComponent(pair.modelDirectoryName)
        if Self.isInstalled(pair: pair, in: root) { return directory }

        let items = try Self.artifacts(for: pair)
        try Self.checkSpace(at: root)

        progress.totalBytes = Int64(items.reduce(0) { $0 + $1.downloadBytes })
        await report()

        // Everything is assembled in a private staging directory and published
        // with a single move. Writing files straight into place would let a
        // crash — or a reader arriving mid-download — see a directory holding a
        // config and a half-written model, which reads as installed and then
        // fails inside the engine. A directory is either wholly there or not.
        let staging = root.appendingPathComponent(".staging-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: staging,
                                                withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: staging) }

        for artifact in items {
            try await fetch(artifact, pair: pair, into: staging)
        }
        try Self.writeConfig(for: pair, into: staging)

        _ = try? FileManager.default.removeItem(at: directory)
        try FileManager.default.moveItem(at: staging, to: directory)
        return directory
    }

    /// Refuses to start rather than filling the disk and failing mid-write.
    /// Three tiny-model files plus room to inflate come to well under 128 MB.
    private static func checkSpace(at root: URL) throws {
        let probe = FileManager.default.fileExists(atPath: root.path)
            ? root : root.deletingLastPathComponent()
        guard let values = try? probe.resourceValues(
                forKeys: [.volumeAvailableCapacityForImportantUsageKey]),
              let available = values.volumeAvailableCapacityForImportantUsage
        else { return }   // unknown capacity is not evidence of a full disk
        let needed: Int64 = 128 * 1024 * 1024
        guard available > needed else {
            throw Err.insufficientSpace(needed: needed, available: available)
        }
    }

    private func fetch(_ artifact: Artifact,
                       pair: LanguagePair,
                       into directory: URL) async throws {
        let remote = source.baseURL
            .appendingPathComponent(source.directoryName("\(pair.source)\(pair.target)"))
            .appendingPathComponent(artifact.remoteName + source.compressionSuffix)

        progress.file = artifact.localName
        await report()

        let base = completedBytes
        let data = try await fetcher(remote) { [weak self] received in
            // Hops onto the actor to mutate progress; the fetcher calls this
            // from whatever queue URLSession delivers on.
            Task { await self?.advance(to: base + received) }
        }

        let payload = source.compressionSuffix == ".gz"
            ? try Self.gunzip(data, file: artifact.remoteName)
            : data
        try Self.verify(payload, against: artifact.sha256, file: artifact.localName)

        // Plain write: the staging directory is private to this download and
        // published only once complete, so there is no half state for anyone
        // else to observe here.
        try payload.write(to: directory.appendingPathComponent(artifact.localName),
                          options: .atomic)

        // Settle on the pinned size rather than whatever arrived, so rounding
        // in the chunk stream cannot leave the bar a hair short of the mark.
        completedBytes = base + Int64(artifact.downloadBytes)
        await advance(to: completedBytes)
    }

    /// Never moves backwards: chunk callbacks can be delivered out of order
    /// once they hop onto the actor, and a bar that retreats reads as a fault.
    ///
    /// The pinned total is a denominator for display, not an integrity claim —
    /// a mirror that re-compressed the same content would move a different
    /// number of bytes while still passing the digest check, which is correct
    /// and must not fail the download. So the count is clamped for the bar's
    /// sake and the discrepancy is otherwise ignored; each finished file then
    /// settles on its pinned size, which keeps the end landing exactly on 1.0.
    private func advance(to received: Int64) async {
        guard received > progress.receivedBytes else { return }
        progress.receivedBytes = progress.totalBytes > 0
            ? min(received, progress.totalBytes)
            : received
        if progress.totalBytes > 0 {
            progress.fraction = Double(progress.receivedBytes) / Double(progress.totalBytes)
        }
        await report()
    }

    private func report() async {
        let snapshot = progress
        Task { @MainActor in onProgress(snapshot) }
    }

    // MARK: - Transport

    /// Downloads one URL, reporting cumulative bytes as chunks arrive.
    ///
    /// `URLSession.data(from:)` would be shorter but reports nothing until it
    /// is finished, which on a 12 MB file means a bar that sits at zero and
    /// then jumps. A data-task delegate hands over each chunk, which is what
    /// makes the fraction move.
    public static let streamingFetch: Fetch = { url, onBytes in
        let delegate = ChunkCollector(onBytes: onBytes)
        let session = URLSession(configuration: .ephemeral,
                                 delegate: delegate, delegateQueue: nil)
        defer { session.finishTasksAndInvalidate() }
        // The URLSessionTask is reachable from the cancellation handler, so
        // abandoning the download actually stops the transfer. Without this the
        // continuation would simply stop being awaited while the bytes kept
        // arriving — which is the difference between cancelling a wait and
        // cancelling a download.
        let handle = TaskHandle()
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                delegate.attach(continuation, file: url.lastPathComponent)
                let task = session.dataTask(with: url)
                handle.adopt(task)
                task.resume()
            }
        } onCancel: {
            handle.cancel()
        }
    }

    /// Bridges a `URLSessionTask` to structured cancellation. Handles the race
    /// where cancellation arrives before the task has been created.
    private final class TaskHandle: @unchecked Sendable {
        private let lock = NSLock()
        private var task: URLSessionTask?
        private var cancelled = false

        func adopt(_ task: URLSessionTask) {
            lock.lock(); defer { lock.unlock() }
            if cancelled { task.cancel() } else { self.task = task }
        }

        func cancel() {
            lock.lock(); defer { lock.unlock() }
            cancelled = true
            task?.cancel()
        }
    }

    /// Accumulates a response chunk by chunk. `@unchecked Sendable` because
    /// URLSession serialises delegate callbacks onto one queue, and the
    /// continuation is written before the task starts.
    private final class ChunkCollector: NSObject, URLSessionDataDelegate, @unchecked Sendable {
        private let onBytes: @Sendable (Int64) -> Void
        private var continuation: CheckedContinuation<Data, Error>?
        private var file = ""
        private var buffer = Data()
        private var received: Int64 = 0
        private var status = 200

        init(onBytes: @escaping @Sendable (Int64) -> Void) {
            self.onBytes = onBytes
        }

        func attach(_ continuation: CheckedContinuation<Data, Error>, file: String) {
            self.continuation = continuation
            self.file = file
        }

        func urlSession(_ session: URLSession,
                        dataTask: URLSessionDataTask,
                        didReceive response: URLResponse,
                        completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
            status = (response as? HTTPURLResponse)?.statusCode ?? 200
            if response.expectedContentLength > 0 {
                buffer.reserveCapacity(Int(response.expectedContentLength))
            }
            completionHandler(.allow)
        }

        func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {
            buffer.append(data)
            received += Int64(data.count)
            onBytes(received)
        }

        func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
            defer { continuation = nil }
            if let error {
                continuation?.resume(throwing: error)
            } else if status != 200 {
                continuation?.resume(throwing: Err.httpStatus(status, file: file))
            } else {
                continuation?.resume(returning: buffer)
            }
        }
    }

    // MARK: - Integrity

    static func verify(_ data: Data, against expected: String, file: String) throws {
        let actual = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        guard actual == expected else {
            throw Err.digestMismatch(file: file, expected: expected, actual: actual)
        }
    }

    /// Inflate a gzip member.
    ///
    /// `Compression` only does raw DEFLATE, so the gzip wrapper is parsed here:
    /// header, optional extra/name/comment/CRC fields, then the deflate stream.
    /// The trailing CRC-32 is deliberately not checked — every file that
    /// carries a digest is verified with SHA-256 instead, which is strictly
    /// stronger and also catches substitution rather than only corruption.
    static func gunzip(_ data: Data, file: String) throws -> Data {
        let bytes = [UInt8](data)
        guard bytes.count > 18, bytes[0] == 0x1f, bytes[1] == 0x8b, bytes[2] == 0x08 else {
            throw Err.notGzip(file: file)
        }
        let flags = bytes[3]
        var offset = 10
        func need(_ n: Int) throws {
            guard offset + n <= bytes.count else { throw Err.notGzip(file: file) }
        }
        if flags & 0x04 != 0 {                     // FEXTRA
            try need(2)
            let length = Int(bytes[offset]) | Int(bytes[offset + 1]) << 8
            offset += 2 + length
        }
        if flags & 0x08 != 0 {                     // FNAME
            while offset < bytes.count, bytes[offset] != 0 { offset += 1 }
            offset += 1
        }
        if flags & 0x10 != 0 {                     // FCOMMENT
            while offset < bytes.count, bytes[offset] != 0 { offset += 1 }
            offset += 1
        }
        if flags & 0x02 != 0 { offset += 2 }       // FHCRC
        guard offset < bytes.count - 8 else { throw Err.notGzip(file: file) }

        let deflated = data.subdata(in: offset ..< (bytes.count - 8))
        // The gzip trailer's ISIZE is the uncompressed size mod 2^32, which is
        // the right first guess for the buffer; grown below if it was a lie.
        let isize = bytes[(bytes.count - 4)...].enumerated()
            .reduce(0) { $0 | Int($1.element) << (8 * $1.offset) }
        var capacity = max(isize, deflated.count * 4) + 4096

        for _ in 0 ..< 8 {
            var output = Data(count: capacity)
            let written = output.withUnsafeMutableBytes { dst -> Int in
                deflated.withUnsafeBytes { src -> Int in
                    compression_decode_buffer(
                        dst.bindMemory(to: UInt8.self).baseAddress!, capacity,
                        src.bindMemory(to: UInt8.self).baseAddress!, deflated.count,
                        nil, COMPRESSION_ZLIB)
                }
            }
            // A full buffer is ambiguous — it may have been exactly enough, or
            // truncated — so grow and retry rather than return a short file.
            if written > 0, written < capacity {
                return output.prefix(written)
            }
            capacity *= 2
        }
        throw Err.inflateFailed(file: file)
    }

    /// Bergamot is configured by file, so the config is generated rather than
    /// downloaded: it is the same for every direction but the three filenames,
    /// and Mozilla does not publish one.
    static func writeConfig(for pair: LanguagePair, into directory: URL) throws {
        let p = "\(pair.source)\(pair.target)"
        let yaml = """
        relative-paths: true
        models:
          - model.\(p).intgemm.alphas.bin
        vocabs:
          - vocab.\(p).spm
          - vocab.\(p).spm
        shortlist:
            - lex.50.50.\(p).s2t.bin
            - false
        beam-size: 1
        normalize: 1.0
        word-penalty: 0
        mini-batch: 1
        maxi-batch: 1
        maxi-batch-sort: src
        workspace: 2000
        max-length-factor: 2.5
        gemm-precision: int8shiftAlphaAll
        mini-batch-words: 1024
        max-length-break: 128
        ssplit-mode: sentence

        """
        try yaml.write(to: directory.appendingPathComponent("config.bergamot.yml"),
                       atomically: true, encoding: .utf8)
    }
}
