import Compression
import CryptoKit
import Foundation

/// Fetches Bergamot translation models for one language direction into the
/// layout `Translator` reads: `<root>/moz-<pair>/` holding three model files and
/// a generated `config.bergamot.yml`.
///
/// Shaped after `OnboardingDownloader` — an actor holding progress state,
/// snapshotting it out to a `@MainActor` callback, entered through one static
/// `download`. It does not share that type's machinery, because it cannot:
/// `ModelUtils.resolveOrDownloadModel` resolves Hugging Face *repos* of
/// safetensors into the MLX cache, and these are three loose gzipped files
/// verified against a digest Mozilla publishes separately. The shape is copied;
/// the transport is not.
///
/// ## Where the bytes come from, and why that is safe
///
/// Mozilla publishes these models in `mozilla/firefox-translations-models`, but
/// the weight files there are Git-LFS pointers whose objects now answer
/// **410 Gone** — that repository can no longer serve them. What it does still
/// serve is `models/<tier>/<pair>/metadata.json`, a small plain file carrying
/// the SHA-256 of the model weights. The bytes come from a community mirror.
///
/// Nothing downloaded is trusted. Every file is checked against a digest pinned
/// in `TranslationModelDigests`, generated by
/// `Scripts/generate-translation-manifest.py`, which corroborates each model
/// digest against Mozilla's published hash. The mirror is transport only: a
/// substituted file fails `verify(_:against:)` and the download throws.
///
/// One measured caveat, recorded because it is not obvious: the mirror carries
/// the best tier available per direction, not one tier throughout — `ruen` is
/// the 17 MB tiny model while `deen` and `fien` are the 32 MB ones. Every
/// direction still matches *some* published Mozilla hash; the tier is noted per
/// entry in the generated manifest.
public actor TranslationDownloader {
    /// Progress for one direction, in bytes actually transferred.
    public struct Progress: Sendable {
        /// Received over total compressed bytes for all three files (0…1).
        ///
        /// Denominated in transferred bytes, not files completed: the three
        /// files differ by more than an order of magnitude, so a per-file
        /// fraction would sit still through the long one and then leap.
        public var fraction = 0.0
        /// Bytes received so far across the whole direction.
        public var receivedBytes: Int64 = 0
        /// Total to transfer, known up front from the pinned manifest.
        public var totalBytes: Int64 = 0
        /// The file currently arriving, for a label.
        public var file = ""
        public init() {}
    }

    /// Fetches one URL, reporting cumulative bytes as they arrive.
    ///
    /// Injectable so progress reporting can be tested without a network: a fake
    /// can deliver known chunk sizes and the assertions stay deterministic.
    public typealias Fetch = @Sendable (URL, @escaping @Sendable (Int64) -> Void) async throws -> Data

    /// One downloadable file, the digest its contents must match, and how many
    /// bytes it costs to fetch.
    ///
    /// `sha256` is mandatory, and deliberately not optional. Every file here is
    /// loaded by the engine — the vocabulary and the lexical shortlist steer
    /// decoding just as the weights do — so an unpinned one is an unverified
    /// input from a mirror nobody audits. An optional digest would let a
    /// direction be added with verification silently skipped; requiring it
    /// makes that a compile error instead.
    ///
    /// The digest covers the *decompressed* file: it is what the engine loads,
    /// so verifying it catches both a corrupted transfer and a substituted
    /// archive. `downloadBytes` is the *compressed* length, because that is
    /// what travels.
    public struct Artifact: Sendable {
        public let remoteName: String
        public let localName: String
        public let sha256: String
        public let downloadBytes: Int

        public init(remoteName: String, localName: String, sha256: String, downloadBytes: Int) {
            self.remoteName = remoteName
            self.localName = localName
            self.sha256 = sha256
            self.downloadBytes = downloadBytes
        }
    }

    /// Where to fetch from and how the files are named there. Configurable so a
    /// mirror change is a value change, not an edit to the download logic.
    public struct Source: Sendable {
        /// Directory URL under which each direction has a folder.
        public let baseURL: URL
        /// `ruen` → the remote folder name. Mirrors differ: `ru-en` and `ru_en`
        /// are both in use.
        public let directoryName: @Sendable (String) -> String
        /// Suffix on remote files; "" when they are stored uncompressed.
        public let compressionSuffix: String

        public init(baseURL: URL,
                    directoryName: @escaping @Sendable (String) -> String,
                    compressionSuffix: String) {
            self.baseURL = baseURL
            self.directoryName = directoryName
            self.compressionSuffix = compressionSuffix
        }

        /// Gzipped mirror of the Mozilla models, pinned to one revision so a
        /// later push cannot change what a released Murmur downloads.
        public static let mozillaMirror = Source(
            baseURL: URL(string:
                "https://huggingface.co/mukowaty/firefox-translations/resolve/main")!,
            directoryName: { pair in
                let cut = pair.index(pair.startIndex, offsetBy: 2)
                return "\(pair[..<cut])-\(pair[cut...])"
            },
            compressionSuffix: ".gz")

        /// Our own CTranslate2 conversions of the Helsinki tc-big models, used
        /// for the text that actually gets pasted.
        ///
        /// Served uncompressed: gzip takes 248.9 MB to 227.0 MB on int8
        /// weights, and inflating a quarter of a gigabyte is not worth 8.8%.
        public static let murmurQualityMirror = Source(
            baseURL: URL(string:
                "https://huggingface.co/beshkenadze/murmur-translation-ct2/resolve/main")!,
            directoryName: { pair in
                let cut = pair.index(pair.startIndex, offsetBy: 2)
                return "\(pair[..<cut])-\(pair[cut...])"
            },
            compressionSuffix: "")
    }

    /// Which tier of model a downloader instance installs.
    ///
    /// One instance serves one kind. The download machinery below - staging
    /// registry, sweep-before-space-check, digest verification, the join/cancel
    /// guard - is identical for both and was hard enough to get right once;
    /// a second downloader would have to re-earn all of it.
    public enum Kind: String, Sendable {
        /// bergamot student, ~22 MB, installed for every chosen direction.
        case fast
        /// opus-mt tc-big under CTranslate2, ~253 MB, installed on demand.
        case quality

        func directoryName(for pair: LanguagePair) -> String {
            switch self {
            case .fast: return pair.modelDirectoryName
            case .quality: return pair.qualityModelDirectoryName
            }
        }

        /// The file whose presence means "installed". For the fast tier that is
        /// the generated config, which is written last; for the quality tier
        /// there is no generated file, so it is the weights.
        var sentinelFile: String {
            switch self {
            case .fast: return "config.bergamot.yml"
            case .quality: return "model.bin"
            }
        }
    }

    public enum Err: Error, Equatable {
        case httpStatus(Int, file: String)
        /// The bytes are not what the manifest pins. Never retried silently: a
        /// mismatch means the mirror is wrong or hostile, and quietly
        /// translating with unknown weights is worse than not translating.
        case digestMismatch(file: String, expected: String, actual: String)
        /// No pinned digests for this direction, so nothing can be verified.
        /// Refused rather than downloaded unchecked.
        case unpinnedDirection(String)
        case notGzip(file: String)
        case inflateFailed(file: String)
        case insufficientSpace(needed: Int64, available: Int64)
        /// A quality download is already writing to disk. Quality downloads
        /// are serialized (see `StagingRegistry`'s quality slot) rather than
        /// space-checked against each other's live progress, so this is the
        /// honest refusal for a second one arriving mid-download, not a
        /// disk-space problem.
        case qualityDownloadBusy
    }

    private let source: Source
    private let kind: Kind
    private let root: URL
    private let fetcher: Fetch
    private let freeSpace: FreeSpace
    private let onProgress: @MainActor @Sendable (Progress) -> Void
    private var progress = Progress()
    /// Bytes from files already finished, so the fraction keeps climbing across
    /// file boundaries instead of restarting at each one.
    private var completedBytes: Int64 = 0

    private init(source: Source,
                 kind: Kind,
                 root: URL,
                 fetcher: @escaping Fetch,
                 freeSpace: @escaping FreeSpace = TranslationDownloader.realFreeSpace,
                 onProgress: @escaping @MainActor @Sendable (Progress) -> Void) {
        self.source = source
        self.kind = kind
        self.root = root
        self.fetcher = fetcher
        self.freeSpace = freeSpace
        self.onProgress = onProgress
    }

    /// Download one direction, reporting fractions on the main actor.
    ///
    /// Returns without touching the network when the direction is already
    /// complete on disk, so this is safe to call before every translation.
    ///
    /// Concurrent calls for the same direction and root share one download
    /// rather than racing. Note the consequence: the second caller's
    /// `onProgress` never fires, because there is only one download to report
    /// on. It still gets the finished directory or the same error.
    @discardableResult
    public static func download(
        pair: LanguagePair,
        into root: URL,
        kind: Kind = .fast,
        from source: Source? = nil,
        fetcher: @escaping Fetch = TranslationDownloader.streamingFetch,
        freeSpace: @escaping FreeSpace = TranslationDownloader.realFreeSpace,
        onProgress: @escaping @MainActor @Sendable (Progress) -> Void = { _ in }
    ) async throws -> URL {
        // Each kind has exactly one mirror it can come from, so the default is
        // derived rather than passed. An explicit `source` is still accepted,
        // for tests that serve from a local file URL.
        let resolved = source ?? (kind == .quality ? .murmurQualityMirror
                                                   : .mozillaMirror)
        let downloader = TranslationDownloader(source: resolved, kind: kind,
                                               root: root,
                                               fetcher: fetcher, freeSpace: freeSpace,
                                               onProgress: onProgress)
        // Keyed by the install directory, which already differs per kind
        // (`moz-ruen` against `ct2-ruen`), so a fast and a quality download of
        // the same direction do not share a task.
        let key = "\(root.standardizedFileURL.path)|\(kind.directoryName(for: pair))"
        return try await awaitShared(key: key) {
            try await downloader.run(pair: pair)
        }
    }

    /// Holds one in-flight download per `(root, direction)`, and keeps it alive
    /// exactly as long as somebody is waiting on it.
    ///
    /// `TranslationDownloader` is an actor, but a fresh one is built per call,
    /// so its isolation serialises nothing across callers. Without this, two
    /// concurrent downloads of the same direction would publish over each
    /// other — and the loser could delete a directory the winner had already
    /// put in place, leaving an installation that is neither present nor
    /// absent. Sharing the task also avoids fetching 20 MB twice.
    ///
    /// Waiters are counted rather than assumed, because sharing a task means no
    /// single caller may cancel it: abandoning one language while another
    /// caller still wants the same pair must not cut that caller off. The
    /// download stops only when the last waiter leaves — which is what makes
    /// scrubbing through the picker stop the network instead of merely stopping
    /// the wait.
    /// Internal rather than private so the join/leave invariants can be tested
    /// directly: the cancelled-entry window they close is a race that a
    /// timing-based test cannot reliably reproduce.
    actor Coordinator {
        static let shared = Coordinator()

        private struct Entry {
            let task: Task<URL, Error>
            /// One token per waiter. A set, not a count, so a waiter that both
            /// cancels and then completes cannot decrement twice.
            var waiters: Set<UUID>
        }

        private var inFlight: [String: Entry] = [:]

        func join(key: String,
                  work: @escaping @Sendable () async throws -> URL) -> (Task<URL, Error>, UUID) {
            let token = UUID()
            // A cancelled task is never joined. `leave` cancels and unregisters,
            // but it runs as its own hop onto this actor, so there is a window
            // where a cancelled entry is still listed. Picking a language,
            // switching away, and picking it again lands squarely in it — and
            // joining there would hand back a task that fails instantly, so the
            // model would silently never download.
            if var existing = inFlight[key], !existing.task.isCancelled {
                existing.waiters.insert(token)
                inFlight[key] = existing
                return (existing.task, token)
            }
            let task = Task { try await work() }
            inFlight[key] = Entry(task: task, waiters: [token])
            return (task, token)
        }

        /// Drop one waiter; cancel the shared download when the last one goes.
        func leave(key: String, token: UUID) {
            guard var entry = inFlight[key] else { return }
            entry.waiters.remove(token)
            if entry.waiters.isEmpty {
                entry.task.cancel()
                inFlight[key] = nil
            } else {
                inFlight[key] = entry
            }
        }
    }

    /// Await a shared download, leaving cleanly whether it finishes, fails, or
    /// this caller is cancelled.
    private static func awaitShared(key: String,
                                    work: @escaping @Sendable () async throws -> URL) async throws -> URL {
        let (task, token) = await Coordinator.shared.join(key: key, work: work)
        do {
            let url = try await withTaskCancellationHandler {
                try await task.value
            } onCancel: {
                Task { await Coordinator.shared.leave(key: key, token: token) }
            }
            await Coordinator.shared.leave(key: key, token: token)
            return url
        } catch {
            await Coordinator.shared.leave(key: key, token: token)
            throw error
        }
    }

    /// Whether every file the engine needs is already present.
    ///
    /// Presence only — the digest was checked when the file was written, and
    /// re-hashing 17 MB before each utterance would cost more than it protects.
    public static func isInstalled(pair: LanguagePair, in root: URL,
                                   kind: Kind = .fast) -> Bool {
        guard let items = try? artifacts(for: pair, kind: kind) else { return false }
        let directory = root.appendingPathComponent(kind.directoryName(for: pair))
        return items.allSatisfy {
            FileManager.default.fileExists(
                atPath: directory.appendingPathComponent($0.localName).path)
        } && FileManager.default.fileExists(
            atPath: directory.appendingPathComponent(kind.sentinelFile).path)
    }

    /// Total compressed bytes for one direction, from the pinned manifest, or
    /// nil when the direction is unpinned.
    ///
    /// Public because a caller spanning several directions — a pivot is two —
    /// has to know the whole size before the first byte moves. Without it the
    /// only honest bar for a pivot would be per-leg, and legs are not equal:
    /// 17 MB followed by 43 MB is not two halves.
    public static func expectedDownloadBytes(for pair: LanguagePair,
                                             kind: Kind = .fast) -> Int64? {
        let p = "\(pair.source)\(pair.target)"
        switch kind {
        case .fast:
            guard let pinned = TranslationModelDigests.all[p] else { return nil }
            return Int64(pinned.totalDownloadBytes)
        case .quality:
            guard let pinned = TranslationQualityDigests.all[p] else { return nil }
            return Int64(pinned.totalBytes)
        }
    }

    /// The three files one direction needs, in the naming Bergamot expects.
    ///
    /// Throws for a direction with no pinned digests rather than returning
    /// artifacts that cannot be checked.
    static func artifacts(for pair: LanguagePair,
                          kind: Kind = .fast) throws -> [Artifact] {
        let p = "\(pair.source)\(pair.target)"
        if kind == .quality {
            guard let pinned = TranslationQualityDigests.all[p] else {
                throw Err.unpinnedDirection(p)
            }
            // Remote and local names match: the shim reads the directory as
            // ct2-opus-mt-converter wrote it, so renaming would only create a
            // mapping to get wrong.
            return pinned.files.map {
                Artifact(remoteName: $0.name, localName: $0.name,
                         sha256: $0.sha256, downloadBytes: $0.bytes)
            }
        }
        guard let pinned = TranslationModelDigests.all[p] else {
            throw Err.unpinnedDirection(p)
        }
        return [
            Artifact(remoteName: "model.\(p).intgemm.alphas.bin",
                     localName: "model.\(p).intgemm.alphas.bin",
                     sha256: pinned.model.sha256,
                     downloadBytes: pinned.model.downloadBytes),
            Artifact(remoteName: "vocab.\(p).spm", localName: "vocab.\(p).spm",
                     sha256: pinned.vocab.sha256,
                     downloadBytes: pinned.vocab.downloadBytes),
            Artifact(remoteName: "lex.50.50.\(p).s2t.bin",
                     localName: "lex.50.50.\(p).s2t.bin",
                     sha256: pinned.lexicon.sha256,
                     downloadBytes: pinned.lexicon.downloadBytes),
        ]
    }

    private func run(pair: LanguagePair) async throws -> URL {
        let directory = root.appendingPathComponent(kind.directoryName(for: pair))
        if Self.isInstalled(pair: pair, in: root, kind: kind) { return directory }

        let items = try Self.artifacts(for: pair, kind: kind)

        // Everything is assembled in a private staging directory and published
        // with a single move. Writing files straight into place would let a
        // crash — or a reader arriving mid-download — see a directory holding a
        // config and a half-written model, which reads as installed and then
        // fails inside the engine. A directory is either wholly there or not.
        //
        // Unique per download so a cancelled run still unwinding cannot delete
        // the directory of the run that replaced it. Debris from a process that
        // was killed is reclaimed by the sweep instead: `defer` covers a normal
        // return or a throw but not a kill, and nothing else sweeps, so
        // otherwise every interrupted download would strand up to 43 MB.
        let staging = root.appendingPathComponent(".staging-\(UUID().uuidString)")
        let stagingName = staging.lastPathComponent
        let needed = Self.spaceNeeded(for: items, kind: kind)
        // The quality tier's write phase is serialized (see the slot's own
        // doc comment for why); the fast tier's files are tiny enough that
        // two running at once is not worth the same treatment. Acquired
        // before the sweep/space work below so a second quality download
        // arriving mid-fetch fails at once rather than paying for a disk
        // check it cannot use.
        if kind == .quality {
            guard await StagingRegistry.shared.tryAcquireQualitySlot(stagingName) else {
                throw Err.qualityDownloadBusy
            }
        }
        // Both releases below - the quality slot and the general staging claim
        // - are awaited explicitly on every exit path, not fired-and-forgotten
        // from `defer`. Swift does not allow `await` inside a `defer` body at
        // all, and a `Task { await ... }` spawned from one is not awaited by
        // the function it defers from: measured directly with a minimal
        // repro, the spawned release was still pending in 451 of 500 trials by
        // the time the deferring function had already returned control to its
        // caller. For the quality slot specifically that is not a cosmetic
        // delay - it means an immediate retry of a just-finished download can
        // find a slot that a moment ago looked free, and get refused as
        // "busy" for nothing. `release(stagingName)` is safe to call even when
        // nothing was ever claimed under that name (`checkSpaceAndClaim`
        // throwing before claiming, or the quality slot never having been
        // acquired here) - removing an absent dictionary key is a no-op.
        do {
            // Swept *before* the space check, not after. Stranded staging
            // directories are exactly what fills the disk, so checking first
            // would let old debris refuse the very retry that would clear it
            // — the recovery this sweep exists for would be the one case it
            // could not perform. Ordering this ahead of the claim below is
            // safe: this download's own staging directory does not exist on
            // disk yet - it is not created until well after the claim,
            // further down - so no sweep call, from this download or a
            // concurrent one, can ever find and delete something that was
            // never there to find.
            await StagingRegistry.shared.sweep(in: root)
            // Checking free space and reserving this download's share happen
            // as one atomic step inside the actor, not as a claim here
            // followed later by a separate read of everyone else's
            // reservations. Two downloads racing to claim the same marginal
            // disk must not each see the other's not-yet-committed
            // reservation and both refuse space that was enough for one of
            // them - nor, the failure mode this replaced, both see zero
            // reservations and jointly overrun the disk. An actor processes
            // one call to completion before the next, so whichever of the two
            // calls this actually reaches first gets the space; there is no
            // window between reading and reserving for the other to land in.
            try await StagingRegistry.shared.checkSpaceAndClaim(
                stagingName, needing: needed, available: freeSpace(root))

            progress.totalBytes = Int64(items.reduce(0) { $0 + $1.downloadBytes })
            await report()

            try FileManager.default.createDirectory(at: staging,
                                                    withIntermediateDirectories: true)
            defer { try? FileManager.default.removeItem(at: staging) }

            for artifact in items {
                try await fetch(artifact, pair: pair, into: staging)
            }
            // Only the fast tier needs a config synthesised: ct2-opus-mt-converter
            // already wrote config.json, and it is downloaded and digest-checked
            // like any other file rather than being regenerated here.
            if kind == .fast {
                try Self.writeConfig(for: pair, into: staging)
            }

            _ = try? FileManager.default.removeItem(at: directory)
            try FileManager.default.moveItem(at: staging, to: directory)

            await StagingRegistry.shared.release(stagingName)
            if kind == .quality {
                await StagingRegistry.shared.releaseQualitySlot(stagingName)
            }
            return directory
        } catch {
            await StagingRegistry.shared.release(stagingName)
            if kind == .quality {
                await StagingRegistry.shared.releaseQualitySlot(stagingName)
            }
            throw error
        }
    }

    /// Tracks staging directories owned by a download running right now, so
    /// debris from a killed process can be reclaimed without touching a live
    /// one.
    ///
    /// A registry rather than a naming convention because neither alternative
    /// holds. Sweeping every `.staging-*` would delete a sibling direction's
    /// live directory, and a cancelled download keeps running until it unwinds,
    /// so "no other staging is live" is never guaranteed. Naming the directory
    /// after the pair instead of a UUID is worse still: re-picking the same
    /// language starts a fresh download while the cancelled one is still
    /// unwinding, and its cleanup would delete the new download's directory.
    actor StagingRegistry {
        static let shared = StagingRegistry()
        /// Name to the bytes it reserved. A dictionary rather than a set: two
        /// quality downloads for different pairs run concurrently on purpose
        /// (their dedup key is the install directory, which differs per
        /// pair), so checking and reserving must account for what every
        /// *other* live download has already claimed, not just whether one is
        /// running at all.
        private var live: [String: Int64] = [:]

        func release(_ name: String) { live.removeValue(forKey: name) }

        /// Owner of the single quality-download slot, or nil.
        ///
        /// Quality models are ~250-280 MB. Two running at once would need
        /// `checkSpaceAndClaim` to track bytes each has *already written*, not
        /// bytes each originally asked for - without that, a download that has
        /// consumed 200 of its 280 MB still counts as a full 280 MB reservation
        /// against a second one's check, even though the OS-reported free
        /// space has *already* dropped by that same 200 MB. The two would
        /// subtract those bytes twice and refuse space that is genuinely
        /// there. For at most two quality directions today, serializing the
        /// write phase is the simpler correct answer over a live-updating
        /// reservation ledger; per-pair *state* (progress, errors) stays
        /// independent regardless, so a caller waiting on the slot is never
        /// misattributed the other pair's bar.
        private var qualitySlotOwner: String?

        func tryAcquireQualitySlot(_ name: String) -> Bool {
            guard qualitySlotOwner == nil else { return false }
            qualitySlotOwner = name
            return true
        }

        func releaseQualitySlot(_ name: String) {
            if qualitySlotOwner == name { qualitySlotOwner = nil }
        }

        /// Checks `needed` against what remains once every *other* live
        /// download's reservation is subtracted from `available`, and reserves
        /// it for `name` in the same step if it fits.
        ///
        /// One call, not a check followed later by a separate claim: an actor
        /// runs one call to completion before starting the next, so as long as
        /// nothing in this body suspends (nothing here does - `available` is
        /// computed by the caller and handed in as a plain value), two
        /// downloads racing to claim the same marginal disk cannot each read
        /// zero reservations and jointly overrun it, and cannot each read the
        /// other's reservation and both refuse space that was enough for one
        /// of them. Whichever call this actor happens to run first wins the
        /// space; the loser's rejection reflects a real, already-committed
        /// claim rather than a snapshot that was stale by the time it acted on
        /// it.
        func checkSpaceAndClaim(_ name: String, needing needed: Int64,
                                available: Int64?) throws {
            guard let available else {
                live[name] = needed   // unknown capacity is not evidence of a full disk
                return
            }
            let reservedByOthers = live.filter { $0.key != name }.values.reduce(0, +)
            let effective = available - reservedByOthers
            guard effective > needed else {
                throw Err.insufficientSpace(needed: needed, available: effective)
            }
            live[name] = needed
        }

        /// Remove staging directories no live download owns. Held inside the
        /// actor so a claim cannot land between the check and the removal.
        func sweep(in root: URL) {
            let fm = FileManager.default
            guard let entries = try? fm.contentsOfDirectory(at: root,
                                                            includingPropertiesForKeys: nil) else {
                return
            }
            for entry in entries
            where entry.lastPathComponent.hasPrefix(".staging-")
                && live[entry.lastPathComponent] == nil {
                _ = try? fm.removeItem(at: entry)
            }
        }
    }

    /// Free bytes at `root`, or nil when the volume will not say.
    public typealias FreeSpace = @Sendable (URL) -> Int64?

    public static let realFreeSpace: FreeSpace = { root in
        let probe = FileManager.default.fileExists(atPath: root.path)
            ? root : root.deletingLastPathComponent()
        return (try? probe.resourceValues(
            forKeys: [.volumeAvailableCapacityForImportantUsageKey]))?
            .volumeAvailableCapacityForImportantUsage
    }

    /// Bytes that must be free to install `items`.
    ///
    /// Download size is not install size for the fast tier: its mirror is
    /// gzipped and `downloadBytes` is what travels, while what lands is the
    /// inflated file - ru-en transfers 12.6 MB and writes 17.1 MB, and the
    /// whole direction is 15.0 MB against 22.5 MB on disk. The quality mirror
    /// serves raw bytes, so there the two are equal.
    ///
    /// Staging is published with a rename inside the same volume, so the peak
    /// is one copy rather than two; the margin covers filesystem overhead.
    static func spaceNeeded(for items: [Artifact], kind: Kind) -> Int64 {
        let transferred = items.reduce(Int64(0)) { $0 + Int64($1.downloadBytes) }
        let expansion: Double = kind == .fast ? 1.6 : 1.0
        let margin: Int64 = 32 * 1024 * 1024
        return Int64(Double(transferred) * expansion) + margin
    }

    private func fetch(_ artifact: Artifact,
                       pair: LanguagePair,
                       into directory: URL) async throws {
        let remote = source.baseURL
            .appendingPathComponent(source.directoryName("\(pair.source)\(pair.target)"))
            .appendingPathComponent(artifact.remoteName + source.compressionSuffix)

        progress.file = artifact.localName
        await report()

        let base = completedBytes
        let data = try await fetcher(remote) { [weak self] received in
            // Hops onto the actor to mutate progress; the fetcher calls this
            // from whatever queue URLSession delivers on.
            Task { await self?.advance(to: base + received) }
        }

        let payload = source.compressionSuffix == ".gz"
            ? try Self.gunzip(data, file: artifact.remoteName)
            : data
        try Self.verify(payload, against: artifact.sha256, file: artifact.localName)

        // Plain write: the staging directory is private to this download and
        // published only once complete, so there is no half state for anyone
        // else to observe here.
        try payload.write(to: directory.appendingPathComponent(artifact.localName),
                          options: .atomic)

        // Settle on the pinned size rather than whatever arrived, so rounding
        // in the chunk stream cannot leave the bar a hair short of the mark.
        completedBytes = base + Int64(artifact.downloadBytes)
        await advance(to: completedBytes)
    }

    /// Never moves backwards: chunk callbacks can be delivered out of order
    /// once they hop onto the actor, and a bar that retreats reads as a fault.
    ///
    /// The pinned total is a denominator for display, not an integrity claim —
    /// a mirror that re-compressed the same content would move a different
    /// number of bytes while still passing the digest check, which is correct
    /// and must not fail the download. So the count is clamped for the bar's
    /// sake and the discrepancy is otherwise ignored; each finished file then
    /// settles on its pinned size, which keeps the end landing exactly on 1.0.
    private func advance(to received: Int64) async {
        guard received > progress.receivedBytes else { return }
        progress.receivedBytes = progress.totalBytes > 0
            ? min(received, progress.totalBytes)
            : received
        if progress.totalBytes > 0 {
            progress.fraction = Double(progress.receivedBytes) / Double(progress.totalBytes)
        }
        await report()
    }

    private func report() async {
        let snapshot = progress
        Task { @MainActor in onProgress(snapshot) }
    }

    // MARK: - Transport

    /// Downloads one URL, reporting cumulative bytes as chunks arrive.
    ///
    /// `URLSession.data(from:)` would be shorter but reports nothing until it
    /// is finished, which on a 12 MB file means a bar that sits at zero and
    /// then jumps. A data-task delegate hands over each chunk, which is what
    /// makes the fraction move.
    public static let streamingFetch: Fetch = { url, onBytes in
        let delegate = ChunkCollector(onBytes: onBytes)
        let session = URLSession(configuration: .ephemeral,
                                 delegate: delegate, delegateQueue: nil)
        defer { session.finishTasksAndInvalidate() }
        // The URLSessionTask is reachable from the cancellation handler, so
        // abandoning the download actually stops the transfer. Without this the
        // continuation would simply stop being awaited while the bytes kept
        // arriving — which is the difference between cancelling a wait and
        // cancelling a download.
        let handle = TaskHandle()
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                delegate.attach(continuation, file: url.lastPathComponent)
                let task = session.dataTask(with: url)
                handle.adopt(task)
                task.resume()
            }
        } onCancel: {
            handle.cancel()
        }
    }

    /// Bridges a `URLSessionTask` to structured cancellation. Handles the race
    /// where cancellation arrives before the task has been created.
    private final class TaskHandle: @unchecked Sendable {
        private let lock = NSLock()
        private var task: URLSessionTask?
        private var cancelled = false

        func adopt(_ task: URLSessionTask) {
            lock.lock(); defer { lock.unlock() }
            if cancelled { task.cancel() } else { self.task = task }
        }

        func cancel() {
            lock.lock(); defer { lock.unlock() }
            cancelled = true
            task?.cancel()
        }
    }

    /// Accumulates a response chunk by chunk. `@unchecked Sendable` because
    /// URLSession serialises delegate callbacks onto one queue, and the
    /// continuation is written before the task starts.
    private final class ChunkCollector: NSObject, URLSessionDataDelegate, @unchecked Sendable {
        private let onBytes: @Sendable (Int64) -> Void
        private var continuation: CheckedContinuation<Data, Error>?
        private var file = ""
        private var buffer = Data()
        private var received: Int64 = 0
        private var status = 200

        init(onBytes: @escaping @Sendable (Int64) -> Void) {
            self.onBytes = onBytes
        }

        func attach(_ continuation: CheckedContinuation<Data, Error>, file: String) {
            self.continuation = continuation
            self.file = file
        }

        func urlSession(_ session: URLSession,
                        dataTask: URLSessionDataTask,
                        didReceive response: URLResponse,
                        completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
            status = (response as? HTTPURLResponse)?.statusCode ?? 200
            if response.expectedContentLength > 0 {
                buffer.reserveCapacity(Int(response.expectedContentLength))
            }
            completionHandler(.allow)
        }

        func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {
            buffer.append(data)
            received += Int64(data.count)
            onBytes(received)
        }

        func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
            defer { continuation = nil }
            if let error {
                continuation?.resume(throwing: error)
            } else if status != 200 {
                continuation?.resume(throwing: Err.httpStatus(status, file: file))
            } else {
                continuation?.resume(returning: buffer)
            }
        }
    }

    // MARK: - Integrity

    static func verify(_ data: Data, against expected: String, file: String) throws {
        let actual = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        guard actual == expected else {
            throw Err.digestMismatch(file: file, expected: expected, actual: actual)
        }
    }

    /// Inflate a gzip member.
    ///
    /// `Compression` only does raw DEFLATE, so the gzip wrapper is parsed here:
    /// header, optional extra/name/comment/CRC fields, then the deflate stream.
    /// The trailing CRC-32 is deliberately not checked — every file that
    /// carries a digest is verified with SHA-256 instead, which is strictly
    /// stronger and also catches substitution rather than only corruption.
    static func gunzip(_ data: Data, file: String) throws -> Data {
        let bytes = [UInt8](data)
        guard bytes.count > 18, bytes[0] == 0x1f, bytes[1] == 0x8b, bytes[2] == 0x08 else {
            throw Err.notGzip(file: file)
        }
        let flags = bytes[3]
        var offset = 10
        func need(_ n: Int) throws {
            guard offset + n <= bytes.count else { throw Err.notGzip(file: file) }
        }
        if flags & 0x04 != 0 {                     // FEXTRA
            try need(2)
            let length = Int(bytes[offset]) | Int(bytes[offset + 1]) << 8
            offset += 2 + length
        }
        if flags & 0x08 != 0 {                     // FNAME
            while offset < bytes.count, bytes[offset] != 0 { offset += 1 }
            offset += 1
        }
        if flags & 0x10 != 0 {                     // FCOMMENT
            while offset < bytes.count, bytes[offset] != 0 { offset += 1 }
            offset += 1
        }
        if flags & 0x02 != 0 { offset += 2 }       // FHCRC
        guard offset < bytes.count - 8 else { throw Err.notGzip(file: file) }

        let deflated = data.subdata(in: offset ..< (bytes.count - 8))
        // The gzip trailer's ISIZE is the uncompressed size mod 2^32, which is
        // the right first guess for the buffer; grown below if it was a lie.
        let isize = bytes[(bytes.count - 4)...].enumerated()
            .reduce(0) { $0 | Int($1.element) << (8 * $1.offset) }
        var capacity = max(isize, deflated.count * 4) + 4096

        for _ in 0 ..< 8 {
            var output = Data(count: capacity)
            let written = output.withUnsafeMutableBytes { dst -> Int in
                deflated.withUnsafeBytes { src -> Int in
                    compression_decode_buffer(
                        dst.bindMemory(to: UInt8.self).baseAddress!, capacity,
                        src.bindMemory(to: UInt8.self).baseAddress!, deflated.count,
                        nil, COMPRESSION_ZLIB)
                }
            }
            // A full buffer is ambiguous — it may have been exactly enough, or
            // truncated — so grow and retry rather than return a short file.
            if written > 0, written < capacity {
                return output.prefix(written)
            }
            capacity *= 2
        }
        throw Err.inflateFailed(file: file)
    }

    /// Bergamot is configured by file, so the config is generated rather than
    /// downloaded: it is the same for every direction but the three filenames,
    /// and Mozilla does not publish one.
    static func writeConfig(for pair: LanguagePair, into directory: URL) throws {
        let p = "\(pair.source)\(pair.target)"
        let yaml = """
        relative-paths: true
        models:
          - model.\(p).intgemm.alphas.bin
        vocabs:
          - vocab.\(p).spm
          - vocab.\(p).spm
        shortlist:
            - lex.50.50.\(p).s2t.bin
            - false
        beam-size: 1
        normalize: 1.0
        word-penalty: 0
        mini-batch: 1
        maxi-batch: 1
        maxi-batch-sort: src
        workspace: 2000
        max-length-factor: 2.5
        gemm-precision: int8shiftAlphaAll
        mini-batch-words: 1024
        max-length-break: 128
        ssplit-mode: sentence

        """
        try yaml.write(to: directory.appendingPathComponent("config.bergamot.yml"),
                       atomically: true, encoding: .utf8)
    }
}
