#!/usr/bin/env python3
"""Pin every translation model file Murmur will download.

Why this exists
---------------
Mozilla publishes the models but can no longer serve them: the weight files in
`mozilla/firefox-translations-models` are Git-LFS pointers whose objects answer
410 Gone. The bytes come from a community mirror instead.

A mirror is transport, not authority, so nothing downloaded is trusted:

* the **model** digest is cross-checked against the `hash` Mozilla publishes in
  `models/<tier>/<pair>/metadata.json`. The mirror carries the best tier per
  direction rather than one tier throughout, so all three tiers are searched
  and the matching one recorded. A direction whose model matches no published
  hash is reported and left out.
* **vocab** and **lexicon** have no Mozilla-published digest to check against,
  so they are pinned here from the bytes fetched at generation time. That is
  trust-on-first-use, but the trust is spent once, under review, and frozen
  into the app: afterwards the mirror cannot change those bytes unnoticed.

Run this to regenerate `TranslationModelDigests.swift` when adding a direction
or moving to a different mirror. It downloads roughly 750 MB.
"""

import concurrent.futures as futures
import gzip
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

# Resolved from this file rather than hardcoded, so the script regenerates the
# manifest of whatever checkout it lives in. An absolute path would either fail
# on another clone or, worse, quietly rewrite a different working copy.
REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "MurmurKit/Sources/MurmurKit/TranslationModelDigests.swift"

LANGUAGES = "bg cs de es et fi fr hu it nl pl pt ru sl uk".split()
DIRECTIONS = [f"{l}en" for l in LANGUAGES] + [f"en{l}" for l in LANGUAGES]
TIERS = ("tiny", "base", "base-memory")

MIRROR = "https://huggingface.co/mukowaty/firefox-translations/resolve/main"
MOZILLA = "https://raw.githubusercontent.com/mozilla/firefox-translations-models/main/models"


def fetch(url, timeout=300):
    request = urllib.request.Request(url, headers={"User-Agent": "murmur-manifest"})
    return urllib.request.urlopen(request, timeout=timeout).read()


def published_hashes(direction):
    """Every model digest Mozilla publishes for this direction, by tier."""
    found = {}
    for tier in TIERS:
        try:
            meta = json.loads(fetch(f"{MOZILLA}/{tier}/{direction}/metadata.json", 60))
            found[tier] = (meta["hash"], meta["byteSize"])
        except Exception:
            pass
    return found


def files_for(direction):
    return [
        f"model.{direction}.intgemm.alphas.bin",
        f"vocab.{direction}.spm",
        f"lex.50.50.{direction}.s2t.bin",
    ]


def collect(direction):
    folder = f"{direction[:2]}-{direction[2:]}"
    digests = {}
    for name in files_for(direction):
        compressed = fetch(f"{MIRROR}/{folder}/{name}.gz")
        blob = gzip.decompress(compressed)
        # The compressed length is what actually travels, so it is what a
        # progress bar must be denominated in. Pinned here because the total
        # has to be known before the first byte arrives, not discovered from
        # Content-Length one file at a time.
        digests[name] = (hashlib.sha256(blob).hexdigest(), len(blob), len(compressed))

    model_name = files_for(direction)[0]
    model_digest = digests[model_name][0]
    corroboration = next(
        (tier for tier, (h, _) in published_hashes(direction).items() if h == model_digest),
        None,
    )
    return direction, digests, corroboration


def main():
    rows, unverified = {}, []
    with futures.ThreadPoolExecutor(max_workers=6) as pool:
        for direction, digests, tier in pool.map(collect, DIRECTIONS):
            if tier is None:
                unverified.append(direction)
                print(f"  SKIP {direction}: model matches no Mozilla-published hash", file=sys.stderr)
                continue
            rows[direction] = (digests, tier)
            print(f"  ok {direction} ({tier})", file=sys.stderr)

    lines = [
        "// Generated by Scripts/generate-translation-manifest.py — do not edit by hand.",
        "//",
        "// Each entry pins the exact bytes Murmur will accept for one direction.",
        "// `model` digests are corroborated against the hash Mozilla publishes in",
        "// models/<tier>/<pair>/metadata.json; the tier is noted per direction",
        "// because the mirror carries the best available one rather than a",
        "// uniform tier. `vocab` and `lexicon` have no Mozilla-published digest,",
        "// so they are pinned from bytes fetched when this file was generated.",
        "",
        "/// SHA-256 and download size of every translation model file, by direction.",
        "enum TranslationModelDigests {",
        "    struct File {",
        "        let sha256: String",
        "        /// Compressed length, which is what the transfer actually moves",
        "        /// and therefore what a progress fraction is denominated in.",
        "        let downloadBytes: Int",
        "    }",
        "",
        "    struct Entry {",
        "        let model: File",
        "        let vocab: File",
        "        let lexicon: File",
        "",
        "        var totalDownloadBytes: Int {",
        "            model.downloadBytes + vocab.downloadBytes + lexicon.downloadBytes",
        "        }",
        "    }",
        "",
        "    static let all: [String: Entry] = [",
    ]
    for direction, (digests, tier) in sorted(rows.items()):
        names = files_for(direction)
        size = digests[names[0]][1]
        total = sum(digests[n][2] for n in names)
        lines.append(f'        // {direction}: {tier}, {size / 1e6:.1f} MB unpacked,'
                     f' {total / 1e6:.1f} MB transferred')
        lines.append(f'        "{direction}": Entry(')
        for field, name in zip(("model", "vocab", "lexicon"), names):
            digest, _, compressed = digests[name]
            end = ")," if field == "lexicon" else ","
            lines.append(f'            {field}: File(sha256: "{digest}",')
            lines.append(f'                         downloadBytes: {compressed}){end}')
    lines += ["    ]", "}", ""]

    out = MANIFEST
    with open(out, "w") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {len(rows)} directions to {out}", file=sys.stderr)
    if unverified:
        print(f"UNVERIFIED, omitted: {unverified}", file=sys.stderr)


if __name__ == "__main__":
    main()
