import { readFileSync } from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
const script = readFileSync(new URL('../Resources/content.js', import.meta.url), 'utf8');
const english = JSON.parse(readFileSync(new URL('../Resources/_locales/en/messages.json', import.meta.url)));
const config = { ok:true, ready:true, source:'en', target:'fi', languages:[{code:'en',name:'English'},{code:'fi',name:'Finnish'},{code:'ru',name:'Russian'}], targets:{en:['fi','ru'],fi:['en','ru'],ru:['en','fi']} };
const answer = (request, transform = text => text.toUpperCase()) => ({ok:true,runId:request.runId,requestId:request.requestId,translations:request.groups.flatMap(group=>group.runs.map(run=>({id:run.id,text:transform(run.text)}))),fallbackGroups:0});
function deferred() { let resolve; const promise=new Promise(value=>{resolve=value;});return {promise,resolve}; }
async function until(condition) {for(let i=0;i<200;i++){if(condition())return;await new Promise(resolve=>setTimeout(resolve,5));}assert.fail('Timed out waiting for controller');}
const settle=()=>new Promise(resolve=>setTimeout(resolve,15));
function page(html, handler=request=>answer(request)) {
 const dom=new JSDOM(`<!doctype html><html lang="en"><body>${html}</body></html>`,{url:'https://example.test/page',runScripts:'outside-only',pretendToBeVisual:true});
 const window=dom.window,document=window.document,calls=[];let listener;
 window.browser={i18n:{getMessage:(key, substitution)=>english[key]?.message.replace('$1',substitution??'')||''},runtime:{onMessage:{addListener(value){listener=value;}},async sendMessage(request){calls.push(request);if(request.type==='config')return request.ticket==='00000000-0000-0000-0000-000000000000'?{ok:false,code:'invalidTicket'}:{...config};if(request.type==='cancel')return {ok:true};if(request.type==='progress')return {ok:true,phase:'preparing',fraction:0.42};return handler(request);}}};window.eval(script);
 return {window,document,calls,open:()=>listener({type:'open'}),get translations(){return calls.filter(call=>call.type==='translate');},get bar(){return document.getElementById('murmator-stream')?.shadowRoot;},click(id){this.bar.getElementById(`murmator-${id}`).click();},select(id,value){const element=this.bar.getElementById(`murmator-${id}`);element.value=value;element.dispatchEvent(new window.Event('change'));},done(){return this.bar?.getElementById('murmator-progress').getAttribute('aria-valuenow')==='100';},destroy(){window.close();}};
}
const longPage=Array.from({length:17},(_,i)=>`<p id="p${i}">Paragraph ${i} is ready to read.</p>`).join('');
test('dormant install and reinjection/probes do not collect or call native',()=>{const f=page('<p>Secret</p>');f.window.getComputedStyle=()=>{throw Error('dormant');};f.window.eval(script);f.document.documentElement.dispatchEvent(new f.window.Event('murmator-stream-probe'));assert.equal(f.document.documentElement.getAttribute('data-murmator-stream-ready'),'1');assert.equal(f.calls.length,0);assert.equal(f.bar,undefined);f.destroy();});
test('forged DOM activation cannot collect text or infer',async()=>{const f=page('<p>Secret</p>');let reads=0;const style=f.window.getComputedStyle;f.window.getComputedStyle=(...args)=>{reads++;return style(...args);};const root=f.document.documentElement;root.setAttribute('data-murmator-stream-ticket','00000000-0000-0000-0000-000000000000');root.dispatchEvent(new f.window.Event('murmator-stream-start'));assert.equal(root.getAttribute('data-murmator-stream-received'),'1');await settle();assert.equal(f.calls[0].sample,'');assert.equal(reads,0);assert.equal(f.translations.length,0);assert.equal(f.bar,undefined);f.destroy();});
test('valid Share consumes ticket before collecting sample',async()=>{const f=page('<p>Hello world</p>');const root=f.document.documentElement;root.setAttribute('data-murmator-stream-ticket','12345678-1234-1234-1234-123456789abc');root.dispatchEvent(new f.window.Event('murmator-stream-start'));await until(()=>f.translations.length===1);assert.equal(f.calls[0].sample,'');assert.equal(f.calls[1].sample,'Hello world');assert.equal(f.calls[1].ticket,undefined);f.destroy();});
test('first blocks readable while second batch remains pending',async()=>{const held=deferred();let count=0;const f=page(longPage,request=>++count===2?held.promise:answer(request));await f.open();await until(()=>f.translations.length===2);assert.equal(f.document.querySelector('#p0').textContent,'PARAGRAPH 0 IS READY TO READ.');assert.equal(f.document.querySelector('#p8').textContent,'Paragraph 8 is ready to read.');const percent=+f.bar.getElementById('murmator-progress').getAttribute('aria-valuenow');assert.ok(percent>0&&percent<100);held.resolve(answer(f.translations[1]));await until(()=>f.done());f.destroy();});
test('original toggle during translation includes later completed blocks',async()=>{const held=deferred();let count=0;const f=page(longPage,request=>++count===2?held.promise:answer(request));await f.open();await until(()=>f.translations.length===2);f.click('original');assert.equal(f.document.querySelector('#p0').textContent,'Paragraph 0 is ready to read.');held.resolve(answer(f.translations[1]));await until(()=>f.done());assert.equal(f.document.querySelector('#p10').textContent,'Paragraph 10 is ready to read.');f.click('original');assert.equal(f.document.querySelector('#p10').textContent,'PARAGRAPH 10 IS READY TO READ.');f.destroy();});
test('stop preserves completed blocks and ignores late responses; close restores',async()=>{const held=deferred();let count=0;const f=page(longPage,request=>++count===2?held.promise:answer(request));await f.open();await until(()=>f.translations.length===2);f.click('stop');held.resolve(answer(f.translations[1]));await settle();assert.equal(f.document.querySelector('#p0').textContent,'PARAGRAPH 0 IS READY TO READ.');assert.equal(f.document.querySelector('#p8').textContent,'Paragraph 8 is ready to read.');assert.ok(f.calls.some(call=>call.type==='cancel'));assert.equal(f.translations.length,2);f.click('close');assert.equal(f.document.querySelector('#p0').textContent,'Paragraph 0 is ready to read.');assert.equal(f.bar,undefined);f.destroy();});
test('close during first batch cannot be undone by late output',async()=>{const held=deferred();const f=page('<p>Hello</p>',()=>held.promise);await f.open();await until(()=>f.translations.length===1);f.click('close');held.resolve(answer(f.translations[0]));await settle();assert.equal(f.bar,undefined);assert.equal(f.document.querySelector('p').textContent,'Hello');f.destroy();});
test('language change cancels old generation and retranslates original source',async()=>{const held=deferred();let count=0;const f=page(longPage,request=>++count===2?held.promise:answer(request,text=>request.target==='ru'?`RU ${text}`:text.toUpperCase()));await f.open();await until(()=>f.translations.length===2);f.select('target','ru');await until(()=>f.translations.length>=5);assert.equal(f.translations[2].target,'ru');assert.equal(f.translations[2].groups[0].runs[0].text,'Paragraph 0 is ready to read.');held.resolve(answer(f.translations[1]));await settle();assert.equal(f.document.querySelector('#p0').textContent,'RU Paragraph 0 is ready to read.');assert.equal(f.document.querySelector('#p8').textContent,'RU Paragraph 8 is ready to read.');f.destroy();});
test('repeated activation uses original source and a single header',async()=>{const f=page('<p>Hello</p>');await f.open();await until(()=>f.done());await f.open();await until(()=>f.translations.length===2);assert.equal(f.translations[1].groups[0].runs[0].text,'Hello');assert.equal(f.document.querySelectorAll('#murmator-stream').length,1);f.destroy();});
test('large group splits strict jobs but applies atomically',async()=>{const held=deferred();let count=0;const original=' hello '.repeat(1600);const f=page(`<p>${original}</p>`,request=>++count===2?held.promise:answer(request));await f.open();await until(()=>f.translations.length===2);assert.equal(f.document.querySelector('p').textContent,original);held.resolve(answer(f.translations[1]));await until(()=>f.done());assert.equal(f.document.querySelector('p').textContent,original.toUpperCase());for(const request of f.translations){assert.ok(request.totalCharacters<=4800);assert.ok(request.groups.length<=8);assert.ok(request.groups.flatMap(group=>group.runs).length<=32);}f.destroy();});
test('large formatted group bounds 32 runs and preserves links and whitespace',async()=>{const original=Array.from({length:75},(_,i)=>`<a href="/${i}"> link ${i} </a>`).join('');const f=page(`<p>${original}</p>`);const links=[...f.document.querySelectorAll('a')];await f.open();await until(()=>f.done());assert.equal(f.translations.length,3);assert.equal(f.document.querySelector('a'),links[0]);assert.equal(links[0].textContent,' LINK 0 ');assert.equal(links[0].getAttribute('href'),'/0');f.destroy();});
test('UTF16 split never sends unpaired surrogate',async()=>{const f=page(`<p>${'a'.repeat(4799)}😀${'b'.repeat(100)}</p>`);await f.open();await until(()=>f.done());assert.equal(f.translations[0].totalCharacters,4799);assert.ok(f.translations.flatMap(r=>r.groups.flatMap(g=>g.runs)).every(run=>run.text.isWellFormed()));f.destroy();});
test('forms, code, editable and hidden nodes never cross bridge',async()=>{const f=page('<p>Read <strong>this</strong><code>secret</code> now</p><form>FORM<input value="password"></form><p contenteditable>EDIT</p><p hidden>HIDDEN</p><div style="display:none">NONE</div><span translate="no">KEEP</span>');await f.open();await until(()=>f.done());assert.equal(f.translations.flatMap(r=>r.groups.flatMap(g=>g.runs.map(n=>n.text))).join(''),'Read this now');assert.equal(f.document.querySelector('code').textContent,'secret');f.destroy();});
for(const [name,change] of [['edited',f=>{f.document.querySelector('strong').firstChild.nodeValue='User edit';}],['moved',f=>{f.document.querySelector('aside').append(f.document.querySelector('p'));}],['new inline content',f=>{f.document.querySelector('p').append(f.document.createTextNode(' inserted'));}],['new protection',f=>{f.document.querySelector('p').setAttribute('translate','no');}],['hidden ancestor',f=>{f.document.querySelector('main').style.display='none';}]])test(`${name} blocks are skipped`,async()=>{const held=deferred();const f=page('<main><p>Hello <strong>world</strong></p></main><aside></aside>',()=>held.promise);await f.open();await until(()=>f.translations.length===1);change(f);held.resolve(answer(f.translations[0]));await until(()=>f.done());assert.ok(f.document.querySelector('p').textContent.startsWith('Hello'));f.destroy();});
test('page edits after translation survive toggle and close',async()=>{const f=page('<p>Hello <strong>world</strong></p>');await f.open();await until(()=>f.done());f.document.querySelector('strong').firstChild.nodeValue='Live edit';f.click('original');assert.equal(f.document.querySelector('strong').textContent,'Live edit');f.click('close');assert.equal(f.document.querySelector('strong').textContent,'Live edit');f.destroy();});
test('model download progress is distinct from completed page progress',async()=>{const held=deferred();const f=page('<p>Hello</p>',()=>held.promise);await f.open();await until(()=>f.translations.length===1);await until(()=>f.bar.getElementById('murmator-note').textContent.includes('42%'));assert.equal(f.bar.getElementById('murmator-progress').getAttribute('aria-valuenow'),'0');f.click('close');held.resolve(answer(f.translations[0]));f.destroy();});
test('stale request IDs cannot modify DOM',async()=>{const f=page('<p>Hello</p>',request=>({...answer(request),requestId:'wrong'}));await f.open();await until(()=>f.bar.getElementById('murmator-note').textContent.includes('failed'));assert.equal(f.document.querySelector('p').textContent,'Hello');f.destroy();});
test('missing, duplicate, empty outputs cannot partially apply group',async()=>{for(const kind of ['missing','duplicate','empty']){const f=page('<p>Hello <strong>world</strong></p>',request=>{const result=answer(request);if(kind==='missing')result.translations.pop();if(kind==='duplicate')result.translations.push(result.translations[0]);if(kind==='empty')result.translations[0].text=' ';return result;});await f.open();await until(()=>f.bar.getElementById('murmator-note').textContent.includes('failed'));assert.equal(f.document.querySelector('p').textContent,'Hello world');f.destroy();}});
test('all six locale dictionaries contain all UI keys',()=>{for(const locale of ['en','ru','de','es','fr','fi']){const labels=JSON.parse(readFileSync(new URL(`../Resources/_locales/${locale}/messages.json`,import.meta.url)));assert.deepEqual(Object.keys(labels).sort(),Object.keys(english).sort());for(const value of Object.values(labels))assert.ok(value.message.length);}});
